/**
 * ENCICLOPÉDIA DE UVAS — dados pesquisados (origem "pesquisado").
 *
 * Pesquisa feita em 26/09/2026, uva por uva, em duas fontes:
 *  - Wikipedia (en), artigo da uva → origem, genealogia por DNA, sinônimos, regiões,
 *    viticultura e descrição do vinho. Os artigos citam Robinson/Harding/Vouillamoz (Wine Grapes) e o VIVC.
 *  - Wine Folly, página da uva → perfil de degustação padronizado (dulçor, corpo, tanino,
 *    acidez, faixa de álcool), sabores principais, temperatura de serviço e guarda.
 *
 * Regras seguidas:
 *  - Só entra o que a fonte afirma. Campo sem fonte fica vazio ("Informação não cadastrada").
 *  - Perfil = Wine Folly convertida: Low→baixa/baixo, Medium-Low→media-/medio-, Medium→media/medio,
 *    Medium-High→media+/medio+, High→alta/alto; corpo Light→leve … Full→encorpado; "No tannins"→baixo.
 *    Álcool pela faixa de % com os limites WSET (<11 baixo, 11–13,9 médio, ≥14 alto) → ex.: 13,5–15% = "medio..alto".
 *  - Quando as fontes divergem, o perfil segue a Wine Folly e a descrição mantém a Wikipedia.
 *  - Genealogia: somente pais afirmados por DNA no artigo. Relações "possíveis" ou disputadas ficaram de fora.
 *
 * v2 (26/09/2026): +24 uvas italianas, uvas secundárias completadas, correções de genealogia
 *   (Melon de Bourgogne é filha da Pinot Blanc, não da Pinot Noir; pais da Sangiovese são disputados).
 *  - "Pode ser confundida": somente pares citados como confundidos/comparados na fonte;
 *    o "como diferenciar" usa apenas dados das fontes.
 *
 * Para atualizar: edite este arquivo, aumente `version` e envie (clasp push). A importação roda
 * sozinha na primeira chamada e nunca sobrescreve o que você editou (origem "usuario"/"ia_revisada").
 */
var GRAPE_ENCYCLOPEDIA = (function () {
  var WIKI = 'https://en.wikipedia.org/wiki/';
  var WF = 'https://winefolly.com/grapes/';

  // Aromas que faltavam no vocabulário e aparecem nas fontes.
  var EXTRA_AROMAS = [
    ['Alcatrão', 'Outros', 'Outros'], ['Groselha espinhosa', 'Frutas', 'Frutas de pomar'], ['Figo', 'Frutas', 'Frutas secas e cozidas'],
    ['Ervas secas', 'Herbáceos', 'Herbáceos'], ['Camomila', 'Flores', 'Flores'], ['Gerânio', 'Flores', 'Flores'],
    ['Carambola', 'Frutas', 'Frutas tropicais'], ['Lilás', 'Flores', 'Flores']
  ];

  // p: [dulçor, corpo, tanino, acidez, álcool]
  function P(sweet, body, tannin, acidity, alcohol) {
    return { sweetness: sweet, body: body, tannin: tannin, acidity: acidity, alcohol: alcohol };
  }

  var grapes = [
    // ============================== TINTAS ==============================
    { name: 'Cabernet Sauvignon', color: 'tinta', wiki: 'Cabernet_Sauvignon', wf: 'cabernet-sauvignon',
      origin: 'França (Bordeaux): cruzamento natural do século XVII.',
      synonyms: ['Bouchet', 'Petit-Cabernet', 'Petit-Vidure', 'Vidure', 'Sauvignon Rouge'],
      main_countries: 'França, EUA, Austrália, Itália, Espanha, Chile, Argentina, África do Sul',
      main_regions: 'Bordeaux, Napa Valley, Sonoma, Washington, Coonawarra, Margaret River, Toscana, Rioja',
      ripening: 'Brotação tardia (1–2 semanas depois de Merlot e Cabernet Franc).',
      vigor: 'Rústica e naturalmente de baixo rendimento.', skin_thickness: 'Grossa', berry_size: 'Pequena', bunch_size: 'Cachos soltos',
      disease_sensitivity: 'Boa resistência à maioria das doenças; exceção: oídio.',
      climate: 'Prefere clima quente; em clima frio mostra notas vegetais (pimentão).',
      soils: 'Adapta-se a vários; cascalho é o ideal (Bordeaux); terra rossa (Coonawarra).',
      description: 'Vinho escuro, encorpado, de taninos altos e acidez perceptível. Aromas de cassis, pimentão verde, menta, eucalipto e tabaco. Serviço: 15–20 °C. Guarda: 10+ anos.',
      profile: P('seco', 'encorpado', 'medio+', 'media+', 'medio..alto'),
      flavors: 'cereja negra, cassis, cedro, especiarias doces, grafite',
      aromas_wf: ['Cereja negra', 'Cassis', 'Cedro', 'Grafite'], aromas_wiki: ['Pimentão verde', 'Menta', 'Eucalipto', 'Tabaco'] },

    { name: 'Merlot', color: 'tinta', wiki: 'Merlot', wf: 'merlot',
      origin: 'Bordeaux (França); primeira menção em 1784. O nome vem de "merle" (melro).',
      synonyms: ['Merlau', 'Médoc Noir', 'Crabutet Noir', 'Plant Médoc', 'Picard', 'Langon'],
      main_countries: 'França, Itália, EUA (Califórnia, Washington), Romênia, Austrália, Argentina, Chile',
      main_regions: 'Bordeaux (Pomerol, Saint-Émilion), Napa Valley, Sonoma, Columbia Valley, Friuli',
      ripening: 'Brota cedo; amadurece até duas semanas antes do Cabernet Sauvignon e tende a sobreamadurecer rápido.',
      vigor: 'Fértil e de maturação fácil.', skin_thickness: 'Mais fina que a do Cabernet Sauvignon', berry_size: 'Grande',
      bunch_size: 'Cachos soltos, com asa característica',
      disease_sensitivity: 'Botrytis, míldio, desavinho (coulure) e cigarrinhas.',
      climate: 'Prefere zonas mais frescas; em áreas quentes amadurece cedo demais.', soils: 'Solos frios, especialmente argila ferrosa.',
      description: 'Cor escura azulada, taninos médios, textura macia e aveludada; ameixa, amora e frutas vermelhas. Serviço: 15–20 °C. Guarda: 3–7 anos (os excepcionais, 15+).',
      profile: P('seco', 'medio+', 'medio+', 'media', 'medio..alto'),
      flavors: 'cereja, chocolate, ameixa, louro, baunilha',
      aromas_wf: ['Chocolate', 'Ameixa', 'Louro', 'Baunilha'], aromas_wiki: ['Amora'] },

    { name: 'Cabernet Franc', color: 'tinta', wiki: 'Cabernet_Franc', wf: 'cabernet-franc',
      origin: 'Bordeaux (França), região do Libournais, século XVII.',
      synonyms: ['Bouchet', 'Bouchy', 'Breton', 'Bordo', 'Petit Fer', 'Véron'],
      main_countries: 'França, Itália, Hungria, Canadá, EUA, Argentina',
      main_regions: 'Vale do Loire, Bordeaux, Friuli, Villány, Szekszárd, Napa, Sonoma, Mendoza',
      ripening: 'Brota e amadurece pelo menos uma semana antes do Cabernet Sauvignon.',
      vigor: 'Vigorosa; sensível ao rendimento — excesso de produção gera notas vegetais.',
      skin_thickness: 'Bastante fina', berry_size: 'Pequena, preto-azulada', bunch_size: 'Pequeno a médio, alongado, com asa',
      disease_sensitivity: 'Mais propensa a mutações que o Cabernet Sauvignon.',
      climate: 'Vai bem em climas mais frios que o Cabernet Sauvignon.',
      soils: 'Adapta-se bem; em solos arenosos e de giz dá vinhos mais encorpados.',
      description: 'Vermelho claro e brilhante; mais leve e com taninos mais baixos que o Cabernet Sauvignon. Framboesa, pimentão, cassis, violeta, tabaco, grafite. Serviço: 15–20 °C. Guarda: 2–5 anos (estilos leves) a 5–10+ anos.',
      profile: P('seco', 'medio', 'medio+', 'alta', 'medio'),
      flavors: 'morango, framboesa, pimentão, cascalho, pimenta chili',
      aromas_wf: ['Morango', 'Framboesa', 'Pimentão verde'], aromas_wiki: ['Cassis', 'Violeta', 'Tabaco', 'Grafite'] },

    { name: 'Pinot Noir', color: 'tinta', wiki: 'Pinot_noir', wf: 'pinot-noir',
      origin: 'França (Borgonha); variedade antiga, possivelmente a uma ou duas gerações da videira selvagem.',
      synonyms: ['Pinot Nero', 'Spätburgunder', 'Blauburgunder', 'Blauer Spätburgunder', 'Morillon'],
      main_countries: 'França, EUA, Alemanha, Áustria, Nova Zelândia, Austrália, Itália, Canadá',
      main_regions: 'Borgonha, Champagne, Willamette Valley (Oregon), Russian River Valley (Califórnia), Central Otago, Mornington Peninsula, Baden, Alto Adige',
      ripening: 'Maturação dispersa entre clones (até seis semanas de diferença); o Frühburgunder amadurece cedo.',
      vigor: 'Baixo vigor; baixo rendimento para vinhos tranquilos de qualidade, rendimentos maiores para espumantes.',
      skin_thickness: 'Fina', berry_size: 'Pequena', bunch_size: 'Pequeno, cônico-cilíndrico, em forma de pinha',
      disease_sensitivity: 'Podridão do cacho, oídio, vírus do enrolamento e da folha em leque; sensível a vento, geada e ao nível de produção.',
      climate: 'Climas frios.', soils: 'Argila calcária é o ideal.',
      description: 'Corpo leve a médio, taninos baixos, cor clara (granada). Jovem: frutas vermelhas (cereja, framboesa, morango); com a idade, notas vegetais e de "estábulo". Serviço: 12–15 °C. Guarda: 5–10 anos (os melhores, até 20).',
      profile: P('seco', 'medio', 'baixo', 'media+', 'medio..alto'),
      flavors: 'framboesa, cereja, cogumelo, baunilha, hibisco',
      aromas_wf: ['Framboesa', 'Cogumelo', 'Baunilha'], aromas_wiki: ['Cereja vermelha', 'Morango', 'Suor de cavalo / estábulo'] },

    { name: 'Syrah', color: 'tinta', wiki: 'Syrah', wf: 'syrah',
      origin: 'Sudeste da França (norte do Rhône).',
      synonyms: ['Shiraz', 'Hermitage', 'Candive', 'Marsanne Noir', 'Schiras'],
      main_countries: 'França, Austrália, EUA, Espanha, Argentina, África do Sul, Chile, Suíça',
      main_regions: 'Vale do Rhône, Barossa Valley, Hunter Valley, McLaren Vale, Califórnia, Washington',
      berry_size: 'Varia com o clone (Petite Syrah = pequena; Gros Syrah = grande)',
      disease_sensitivity: 'Síndrome de definhamento (dieback) observada na França desde os anos 1990.',
      climate: 'Moderado a quente; o estilo muda muito com a temperatura.', soils: 'Granito pedregoso.',
      description: 'Corpo médio a pleno, taninos altos. Clima fresco: amora, pimenta-do-reino, menta; clima quente: alcaçuz, cravo, café. Com a idade, couro e terra. Serviço: 15–20 °C. Guarda: 10+ anos.',
      profile: P('seco', 'encorpado', 'medio+', 'media', 'medio..alto'),
      flavors: 'mirtilo, ameixa preta, chocolate ao leite, tabaco, pimenta verde',
      aromas_wf: ['Mirtilo', 'Ameixa preta', 'Chocolate', 'Tabaco'], aromas_wiki: ['Amora', 'Pimenta-do-reino', 'Menta', 'Alcaçuz', 'Cravo', 'Café', 'Couro'] },

    { name: 'Grenache', color: 'tinta', wiki: 'Grenache', wf: 'grenache',
      origin: 'Espanha (Aragão).',
      synonyms: ['Garnacha', 'Garnatxa', 'Cannonau', 'Garnacha Tinta', 'Grenache Noir'],
      main_countries: 'França, Espanha, Austrália, Itália, EUA',
      main_regions: 'Aragão, Rhône, Roussillon, Priorat, Sardenha (Cannonau), Rioja, Navarra, McLaren Vale',
      ripening: 'Brota cedo e precisa de estação longa; amadurece tarde, muitas vezes semanas depois do Cabernet Sauvignon.',
      vigor: 'Vigorosa; exige controle de rendimento.', skin_thickness: 'Fina', bunch_size: 'Compacto (propenso a doenças)',
      disease_sensitivity: 'Desavinho (coulure), podridão do cacho, míldio.',
      climate: 'Quente e seco, mediterrâneo.', soils: 'Quentes, secos e bem drenados: xisto, granito, galets roulés.',
      description: 'Rubi pálido a médio; acidez e tanino baixos; corpo médio a alto; frutas vermelhas especiadas (framboesa, morango); oxida com facilidade. Muito usada em cortes com Syrah, Mourvèdre, Carignan e Cinsault. Serviço: 15–20 °C. Guarda: 10+ anos.',
      profile: P('seco', 'medio+', 'medio', 'media', 'alto'),
      flavors: 'morango cozido, ameixa grelhada, couro, ervas secas, laranja-sanguínea',
      aromas_wf: ['Fruta cozida', 'Couro', 'Ervas secas', 'Laranja'], aromas_wiki: ['Framboesa', 'Morango'] },

    { name: 'Malbec', color: 'tinta', wiki: 'Malbec', wf: 'malbec',
      origin: 'França.',
      synonyms: ['Côt', 'Côt Noir', 'Pressac', 'Noir de Pressac', 'Cahors'],
      main_countries: 'França, Argentina, Chile, EUA, Austrália, Nova Zelândia, África do Sul',
      main_regions: 'Cahors (França), Mendoza (Argentina), Colchagua (Chile), Napa Valley, Paso Robles, Walla Walla',
      ripening: 'Maturação de meia estação.', vigor: 'Pode dar rendimentos altos quando sadia.', skin_thickness: 'Grossa',
      berry_size: 'Menor nos clones argentinos', bunch_size: 'Menor e mais compacto nos clones argentinos',
      disease_sensitivity: 'Muito sensível: geada, desavinho, míldio, podridão.',
      climate: 'Precisa de mais sol e calor que Cabernet Sauvignon e Merlot.',
      soils: 'Melhor em solos calcários, onde dá vinhos escuros e tânicos.',
      description: 'Cor muito escura, taninos robustos, ameixa. Os argentinos são mais macios, de textura aveludada. Serviço: 15–20 °C. Guarda: 5–10 anos.',
      profile: P('seco', 'encorpado', 'medio', 'media-', 'medio..alto'),
      flavors: 'ameixa vermelha, amora, baunilha, tabaco doce, cacau',
      aromas_wf: ['Ameixa', 'Amora', 'Baunilha', 'Tabaco', 'Cacau'], aromas_wiki: [] },

    { name: 'Tempranillo', color: 'tinta', wiki: 'Tempranillo', wf: 'tempranillo',
      origin: 'Espanha.',
      synonyms: ['Tinta Roriz', 'Aragonez', 'Cencibel', 'Tinto Fino', 'Tinta del País', 'Tinta de Toro', 'Ull de Llebre'],
      main_countries: 'Espanha (87% da produção mundial), Portugal, Austrália, África do Sul, EUA, Argentina, Chile, México',
      main_regions: 'Rioja, Ribera del Duero, Toro, Navarra, Valdepeñas, Penedès, Douro, Alentejo',
      ripening: 'Precoce: amadurece semanas antes da maioria das tintas espanholas.',
      skin_thickness: 'Grossa', berry_size: 'Esférica', bunch_size: 'Compacto e cilíndrico',
      disease_sensitivity: 'Pouca resistência a pragas e doenças; muito sensível a intempéries.',
      climate: 'Precisa de frescor para elegância e acidez e de calor para açúcar e cor; clima mediterrâneo continental.',
      soils: 'Calcários; rende pior em áreas arenosas.',
      description: 'Rubi; frutas vermelhas, ameixa, tabaco, baunilha, couro e ervas. Segundo a Wikipedia, acidez e açúcar naturalmente baixos (a Wine Folly indica acidez média-alta). Serviço: 15–20 °C. Guarda: 10+ anos (bons exemplos passam de 20).',
      profile: P('seco', 'medio+', 'medio+', 'media+', 'medio..alto'),
      flavors: 'cereja, figo seco, cedro, tabaco, endro',
      aromas_wf: ['Figo seco', 'Cedro', 'Tabaco'], aromas_wiki: ['Ameixa', 'Baunilha', 'Couro'] },

    { name: 'Sangiovese', color: 'tinta', wiki: 'Sangiovese', wf: 'sangiovese',
      origin: 'Itália.',
      synonyms: ['Brunello', 'Morellino', 'Nielluccio', 'Prugnolo Gentile', 'Sangiovese Grosso', 'Sangiovese Piccolo', 'Corinto Nero'],
      main_countries: 'Itália (dominante), Argentina, Romênia, França (Córsega), EUA (Califórnia), Austrália',
      main_regions: 'Toscana — Chianti, Montalcino (Brunello), Montepulciano (Vino Nobile); Emilia-Romagna, Úmbria, Marche; Córsega',
      ripening: 'Brota cedo e amadurece devagar; colheita tradicionalmente depois de 29 de setembro.',
      vigor: 'Vigorosa, tende à superprodução.', skin_thickness: 'Fina (propensa a podridão em outubros chuvosos)', berry_size: 'Cerca de 19 × 17 mm, ~3 g',
      disease_sensitivity: 'Podridão.',
      climate: 'Estação longa e calor suficiente; calor excessivo dilui os sabores.', soils: 'Ricos em calcário; galestro e alberese.',
      description: 'Cor clara a média; acidez alta; taninos médio+; cereja ácida com notas terrosas e de folha de chá. Genealogia em disputa: um estudo de 2004 apontou Ciliegiolo × Calabrese di Montenuovo como pais; outro estudo de 2007 concluiu que a Ciliegiolo é que seria filha da Sangiovese. Serviço: 15–20 °C. Guarda: 10+ anos.',
      profile: P('seco', 'medio+', 'medio+', 'media+', 'medio..alto'),
      flavors: 'cereja, tomate assado, balsâmico doce, orégano, café expresso',
      aromas_wf: ['Tomate', 'Café'], aromas_wiki: ['Cereja vermelha', 'Terra molhada', 'Chá preto'] },

    { name: 'Nebbiolo', color: 'tinta', wiki: 'Nebbiolo', wf: 'nebbiolo',
      origin: 'Piemonte (Itália); o DNA sugere possível origem em Valtellina (Lombardia). Primeira menção em 1268 ("nibiol", em Rivoli, perto de Turim).',
      synonyms: ['Spanna', 'Picotener', 'Chiavennasca', 'Lampia', 'Michet', 'Brunenta'],
      main_countries: 'Itália; pequenas áreas nos EUA, México, Argentina, Austrália, África do Sul, Uruguai e Chile',
      main_regions: 'Piemonte (Barolo, Barbaresco), Vale de Aosta (Carema), Valtellina; Novara e Vercelli (Spanna)',
      ripening: 'Primeira a brotar e última a amadurecer (colheita de meados a fim de outubro).',
      disease_sensitivity: 'Propensa a desavinho (coulure) e sensível a viroses.',
      climate: 'Precisa de calor; prefere encostas voltadas ao sul/sudoeste (150–300 m).',
      soils: 'Margas calcárias; em solos arenosos o resultado varia.',
      description: 'Tinto de cor clara que ganha tom tijolo-alaranjado com a idade; muito tânico e de acidez alta quando jovem. Aromas dominantes: alcatrão e rosas; também violeta, ervas silvestres, cereja, framboesa, trufa, tabaco e ameixa seca. Pode evoluir por 30+ anos. DNA (2004): relação pai/filho com Freisa, Vespolina, Negrara, Rossola Nera, Brugnola e Bubbierasco; aparentada com a Viognier. Serviço: 12–15 °C.',
      profile: P('seco', 'medio+', 'alto', 'media+', 'medio..alto'),
      flavors: 'cereja, rosa, couro, anis, vaso de barro',
      aromas_wf: ['Rosa', 'Couro', 'Anis'], aromas_wiki: ['Alcatrão', 'Violeta', 'Framboesa', 'Trufa', 'Tabaco', 'Ameixa seca'] },

    { name: 'Barbera', color: 'tinta', wiki: 'Barbera', wf: 'barbera',
      origin: 'Itália: colinas do Monferrato (Piemonte), conhecida desde o século XIII.',
      synonyms: ['Barbera Nera', 'Barberone', 'Lombardesca', 'Ughetta', 'Gaietto'],
      main_countries: 'Itália, EUA (Califórnia), Austrália, Argentina',
      main_regions: "Barbera d'Asti, Nizza DOCG, Barbera d'Alba, Monferrato, Oltrepò Pavese; Mendoza; Central Valley (Califórnia)",
      ripening: 'Amadurece duas semanas antes do Nebbiolo; colheita de fim de setembro a início de outubro.',
      vigor: 'Muito vigorosa; rendimentos altos se a poda não controlar.', bunch_size: 'Varia com o clone; cachos menores dão a melhor qualidade',
      disease_sensitivity: 'Vírus do enrolamento da folha.', climate: 'Adaptável; vai bem em condições quentes.',
      soils: 'Calcários e franco-argilosos; solos arenosos limitam o vigor.',
      description: 'Rubi profundo, acidez alta, taninos baixos; cerejas, amoras e framboesas; ganha com carvalho. Serviço: 15–20 °C. Guarda: 5–10 anos.',
      profile: P('seco', 'medio+', 'baixo', 'alta', 'medio..alto'),
      flavors: 'cereja ácida, alcaçuz, amora, ervas secas, pimenta-do-reino',
      aromas_wf: ['Cereja vermelha', 'Alcaçuz', 'Amora', 'Ervas secas', 'Pimenta-do-reino'], aromas_wiki: ['Framboesa'] },

    { name: 'Dolcetto', color: 'tinta', wiki: 'Dolcetto', wf: 'dolcetto',
      origin: 'Piemonte (Itália); talvez trazida da França ao Monferrato no século XI, ou nascida na vila de Dogliani.',
      synonyms: ['Dolsin', 'Ormeasco', 'Orincasca'],
      main_countries: 'Itália; pequenas áreas nos EUA e Austrália',
      main_regions: "Piemonte: Dogliani DOCG, Dolcetto d'Alba, Ovada, Asti, Diano d'Alba; Ligúria (Ormeasco); Oltrepò Pavese",
      description: 'Cor escura, seco, acidez moderada a baixa, tânico e frutado; cereja negra e alcaçuz, com ameixa seca; final amargo característico que lembra amêndoa. Douce Noire e Charbono, antes tidos como sinônimos, são outras variedades (DNA). Em Oltrepò Pavese é chamada de "Nebbiolo". Serviço: 15–20 °C. Guarda: 3–5 anos.',
      profile: P('seco', 'medio+', 'baixo', 'media-', 'medio'),
      flavors: 'ameixa, amora, cacau, pimenta-do-reino, violeta',
      aromas_wf: ['Ameixa', 'Amora', 'Cacau', 'Pimenta-do-reino', 'Violeta'], aromas_wiki: ['Cereja negra', 'Alcaçuz', 'Ameixa seca', 'Amêndoa'] },

    { name: 'Montepulciano', color: 'tinta', wiki: 'Montepulciano_(grape)', wf: 'montepulciano',
      origin: "Abruzzo (Itália central), talvez na área de Torre de' Passeri.",
      synonyms: ['Cordisco', 'Morellone', 'Primutico', 'Uva Abruzzese', 'Sangiovetto'],
      main_countries: 'Itália; pequenas áreas na Turquia, Austrália, México, Nova Zelândia e EUA',
      main_regions: "Abruzzo (Montepulciano d'Abruzzo DOC, Colline Teramane DOCG), Marche (Rosso Conero, Rosso Piceno), Lazio, Puglia",
      ripening: 'Brotação e maturação tardias.', vigor: 'Produtiva, de alto rendimento.', skin_thickness: 'Grossa', berry_size: 'Graúda',
      disease_sensitivity: 'Boa resistência à botrytis e ao oídio.', climate: 'Adequada a regiões com geadas tardias de primavera.',
      description: 'Rubi profundo (também rosado); segundo a Wikipedia, acidez moderada e taninos macios, "redondo, com ameixa e peso" (a Wine Folly indica taninos e acidez médios-altos). Não confundir com o Vino Nobile di Montepulciano, vinho toscano de Sangiovese. Serviço: 15–20 °C. Guarda: 10+ anos.',
      profile: P('seco', 'medio+', 'medio+', 'media+', 'medio'),
      flavors: 'ameixa vermelha, amora, tomilho seco, especiarias doces, mesquite',
      aromas_wf: ['Ameixa', 'Amora', 'Tomilho'], aromas_wiki: [] },

    { name: 'Primitivo', color: 'tinta', wiki: 'Zinfandel', wf: 'zinfandel',
      origin: 'Provavelmente Montenegro; menções entre 1426 e 1442 ("Kratošija", Budva) e em 1444 ("Tribidrag", Croácia). DNA: idêntica à Zinfandel (EUA) e à Crljenak Kaštelanski (Croácia).',
      synonyms: ['Zinfandel', 'Crljenak Kaštelanski', 'Tribidrag', 'Kratošija'],
      main_countries: 'EUA (Califórnia), Itália, Montenegro, Croácia',
      main_regions: 'Puglia (Primitivo di Manduria); Califórnia (Amador, Dry Creek Valley, Paso Robles, Napa, Lodi); Montenegro',
      ripening: 'Relativamente precoce (o clone Primitivo é precoce); maturação desigual no cacho.',
      vigor: 'Vigorosa.', skin_thickness: 'Fina', bunch_size: 'Grande e compacto',
      disease_sensitivity: 'Podridão do cacho.', climate: 'Quente, mas não demais — no calor excessivo as bagas murcham.',
      description: 'Tinto robusto: framboesa em áreas mais frescas; amora, anis e pimenta nas quentes. Açúcar alto: chega a 15%+ de álcool. Nos EUA, o White Zinfandel (rosé meio-doce) vende 6× mais que o tinto. Serviço: 15–20 °C. Guarda: 5–10 anos.',
      profile: P('seco', 'medio+', 'medio+', 'media-', 'alto'),
      flavors: 'amora, morango, geleia de pêssego, canela, tabaco doce',
      aromas_wf: ['Amora', 'Morango', 'Geleia', 'Canela', 'Tabaco'], aromas_wiki: ['Framboesa', 'Anis', 'Pimenta-do-reino'] },

    { name: 'Aglianico', color: 'tinta', wiki: 'Aglianico', wf: 'aglianico',
      origin: 'Sul da Itália.',
      synonyms: ['Aglianicone', 'Ellenico', 'Gnanico', 'Agliatica'],
      main_countries: 'Itália; pequenas áreas na Austrália, EUA e Canadá',
      main_regions: 'Basilicata (Aglianico del Vulture); Campânia (Taurasi DOCG, Aglianico del Taburno, Falerno del Massico)',
      ripening: 'Brota cedo e amadurece muito tarde (colheita até novembro).',
      disease_sensitivity: 'Boa resistência ao oídio; muito sensível ao míldio; pouca resistência à botrytis.',
      climate: 'Seco e ensolarado.', soils: 'Especialmente vulcânicos.',
      description: 'Granada profundo, acidez alta, taninos firmes e agressivos quando jovem, encorpado; chocolate e ameixa; grande potencial de guarda. Chamado de "Barolo do Sul". Serviço: 15–20 °C. Guarda: 10+ anos.',
      profile: P('seco', 'encorpado', 'alto', 'media+', 'medio..alto'),
      flavors: 'pimenta branca, cereja negra, fumaça, caça, ameixa especiada',
      aromas_wf: ['Pimenta branca', 'Cereja negra', 'Fumaça', 'Caça', 'Ameixa'], aromas_wiki: ['Chocolate'] },

    { name: "Nero d'Avola", color: 'tinta', wiki: 'Nero_d%27Avola', wf: 'nero-davola',
      origin: 'Itália (Sicília).',
      synonyms: ['Calabrese'],
      main_countries: 'Itália, Austrália, Malta, Turquia, África do Sul, EUA',
      main_regions: 'Sicília (Avola, Noto, Pachino, Siracusa)', climate: 'Quente e relativamente seco.',
      description: 'Cor cereja/rubi; seco, levemente ácido, encorpado; amoras e notas apimentadas. Comparado aos Shiraz do Novo Mundo. Serviço: 15–20 °C. Guarda: 10+ anos.',
      profile: P('seco', 'medio+', 'medio+', 'media', 'medio..alto'),
      flavors: 'cereja negra, ameixa preta, alcaçuz, tabaco, pimenta chili',
      aromas_wf: ['Cereja negra', 'Ameixa preta', 'Alcaçuz', 'Tabaco'], aromas_wiki: ['Amora'] },

    { name: 'Carménère', color: 'tinta', wiki: 'Carmenere', wf: 'carmenere',
      origin: 'Médoc (Bordeaux, França).',
      synonyms: ['Grande Vidure', 'Carmenelle', 'Cabernelle'],
      main_countries: 'Chile, Itália, EUA',
      main_regions: 'Colchagua, Rapel, Maipo (Chile); Vêneto e Friuli (Itália); Walla Walla',
      ripening: 'Brota e floresce 3–7 dias depois da Merlot; amadurece 2–3 semanas depois.',
      vigor: 'Rendimento menor que o da Merlot.', disease_sensitivity: 'Desavinho (coulure).',
      climate: 'Estação longa, clima moderado a quente; sofre com primaveras frias e úmidas.',
      soils: 'Vai mal com irrigação ou chuva em excesso.',
      description: 'Vermelho profundo; frutas vermelhas, especiarias e frutas silvestres; taninos mais suaves que os do Cabernet Sauvignon; corpo médio; cereja, defumado, terroso. Melhor jovem. Serviço: 15–20 °C. Guarda: 2–3 anos (os melhores, 10+).',
      profile: P('seco', 'medio', 'medio', 'media+', 'medio..alto'),
      flavors: 'framboesa, pimentão, ameixa preta, baunilha, páprica',
      aromas_wf: ['Framboesa', 'Pimentão verde', 'Ameixa preta', 'Baunilha'], aromas_wiki: ['Defumado'] },

    { name: 'Mourvèdre', color: 'tinta', wiki: 'Mourv%C3%A8dre', wf: 'monastrell-mourvedre',
      origin: 'Costa mediterrânea da Espanha.',
      synonyms: ['Monastrell', 'Mataro', 'Balzac Noir'],
      main_countries: 'França, Espanha, Austrália, EUA, África do Sul',
      main_regions: 'Rhône e Provence; Valência, Alicante, Jumilla; Austrália do Sul, Nova Gales do Sul; Califórnia, Washington',
      ripening: 'Brota e amadurece muito tarde.', vigor: 'Muito vigorosa, com folhagem abundante.',
      skin_thickness: 'Grossa', berry_size: 'Pequena', bunch_size: 'Médio, compacto, cônico',
      disease_sensitivity: 'Oídio e míldio (cachos compactos aumentam o risco).',
      climate: 'Quente — "a cara no sol quente e os pés na água".', soils: 'Argilosos rasos que retêm umidade.',
      description: 'Muito colorido, muito tânico, álcool alto; notas de caça e terrosas com fruta vermelha suave; jovem pode ter aromas de "curral". Serviço: 15–20 °C. Guarda: 10+ anos.',
      profile: P('seco', 'encorpado', 'alto', 'media', 'medio..alto'),
      flavors: 'amora, pimenta-do-reino, cacau, tabaco, carne assada',
      aromas_wf: ['Amora', 'Pimenta-do-reino', 'Cacau', 'Tabaco', 'Carne'], aromas_wiki: ['Caça'] },

    { name: 'Gamay', color: 'tinta', wiki: 'Gamay', wf: 'gamay',
      origin: 'Aldeia de Gamay, ao sul de Beaune (Borgonha), anos 1360.',
      synonyms: ['Gamay Noir à Jus Blanc'],
      main_countries: 'França, Canadá, Suíça, EUA, Austrália',
      main_regions: 'Beaujolais, Loire (Touraine), Península do Niágara, Willamette Valley',
      ripening: 'Amadurece duas semanas antes do Pinot Noir.', vigor: 'Muito vigorosa e produtiva.',
      soils: 'Prefere solos ácidos; rende mal em calcário alcalino.',
      description: 'Tinto leve, de acidez alta; morango e framboesa esmagados, florais (lilás, violeta); cereja ácida, pimenta, frutas secas. Nomes enganosos: "Napa Gamay" é a Valdiguié e "Gamay Beaujolais" é um clone de Pinot Noir. Serviço: 12–15 °C. Guarda: 3–5 anos.',
      profile: P('seco', 'medio-', 'baixo', 'media+', 'baixo..medio'),
      flavors: 'romã, amora silvestre, violeta, terra de vaso, peônia',
      aromas_wf: ['Romã', 'Amora', 'Violeta', 'Terra molhada'], aromas_wiki: ['Morango', 'Framboesa', 'Lilás'] },

    { name: 'Touriga Nacional', color: 'tinta', wiki: 'Touriga_Nacional', wf: 'touriga-nacional',
      origin: 'Portugal.',
      synonyms: ['Mortágua', 'Touriga Fina', 'Tourigo do Dão', 'Tourigo Antigo', 'Preto Mortágua'],
      main_countries: 'Portugal, EUA', main_regions: 'Douro, Dão',
      vigor: 'Muito vigorosa, com um dos menores rendimentos entre as uvas comerciais.', berry_size: 'Pequena a minúscula',
      climate: 'Calor intenso.', soils: 'Encostas íngremes de xisto, "mais pedra que terra".',
      description: 'Vermelho escuro; taninos altos e fruta negra concentrada; intensa, aromática, de muito extrato. Forma com a Touriga Franca uma parceria comparável à de Cabernet Sauvignon e Cabernet Franc. Serviço: 15–20 °C. Guarda: 10+ anos.',
      profile: P('seco', 'encorpado', 'alto', 'media+', 'alto'),
      flavors: 'mirtilo, violeta, ameixa, menta, ardósia molhada',
      aromas_wf: ['Mirtilo', 'Violeta', 'Ameixa', 'Menta', 'Pedra molhada'], aromas_wiki: [] },

    { name: 'Pinotage', color: 'tinta', wiki: 'Pinotage', wf: 'pinotage',
      origin: 'África do Sul: criada em 1924 por Abraham Izak Perold (Universidade de Stellenbosch). A Cinsaut era chamada de "Hermitage" lá, daí o nome.',
      synonyms: [],
      main_countries: 'África do Sul (maioria), Brasil, Canadá, Alemanha, Israel, Nova Zelândia, Suíça, EUA, Zimbábue',
      main_regions: 'Stellenbosch (Simonsberg)', ripening: 'Precoce.',
      vigor: 'Vigorosa; pode render 120 hl/ha, vinhas velhas cerca de 50 hl/ha.',
      description: 'Vermelho profundo; defumado, frutas silvestres e terroso, às vezes com banana e frutas tropicais; naturalmente tânico. Serviço: 15–20 °C. Guarda: 5–10 anos (os melhores, 15+).',
      profile: P('seco', 'encorpado', 'medio+', 'media+', 'alto'),
      flavors: 'cereja negra, amora, figo, menta, caça',
      aromas_wf: ['Cereja negra', 'Amora', 'Figo', 'Menta', 'Caça'], aromas_wiki: ['Defumado', 'Banana'] },

    { name: 'Corvina', color: 'tinta', wiki: 'Corvina', wf: 'corvina',
      origin: 'Vêneto (nordeste da Itália).',
      synonyms: ['Corvina Veronese', 'Cruina'],
      main_countries: 'Itália (7.495 ha em 2010); pequena área na Argentina',
      main_regions: 'Valpolicella, Amarone della Valpolicella DOCG, Recioto della Valpolicella DOCG, Valpolicella Ripasso, Bardolino',
      ripening: 'Tardia; as primeiras gemas não frutificam.', vigor: 'Tende a rendimentos altos, que prejudicam a qualidade.',
      skin_thickness: 'Grossa — ideal para a secagem (appassimento) e protege da podridão', berry_size: 'Pequena',
      soils: 'Argila calcária.',
      description: 'Carmim claro, acidez alta, corpo leve a médio; cereja ácida e nota de amêndoa amarga; pouca cor e pouco tanino. É a base do Amarone (uvas secas). A Corvinone é outra variedade (DNA). Serviço: 12–15 °C. Guarda: 5–10 anos.',
      profile: P('seco', 'medio', 'baixo', 'media+', 'medio..alto'),
      flavors: 'cereja ácida, canela, chocolate, pimenta branca, amêndoa verde',
      aromas_wf: ['Cereja vermelha', 'Canela', 'Chocolate', 'Pimenta branca', 'Amêndoa'], aromas_wiki: [] },

    { name: 'Petit Verdot', color: 'tinta', wiki: 'Petit_Verdot', wf: 'petit-verdot',
      origin: 'Sudoeste da França.',
      synonyms: ['Verdot', 'Petit Verdau', 'Carmelin', 'Heran'],
      main_countries: 'França, Austrália, Argentina, Chile, Itália, Espanha, Portugal, EUA, África do Sul',
      main_regions: 'Bordeaux (Médoc); Ica (Peru); Califórnia; Virgínia',
      ripening: 'Amadurece bem mais tarde que as outras uvas de Bordeaux, muitas vezes tarde demais.',
      vigor: 'Mais de dois cachos por ramo.', berry_size: 'Pequena, preta', bunch_size: 'Pequeno, cilíndrico, com asa',
      climate: 'Prefere climas mais quentes que o de Bordeaux.',
      description: 'Acrescenta tanino, cor e sabor aos cortes e reforça o meio de boca do Cabernet Sauvignon. Jovem: banana e aparas de lápis; com a idade, violeta e couro. Serviço: 15–20 °C. Guarda: 10+ anos.',
      profile: P('seco', 'encorpado', 'alto', 'media', 'medio..alto'),
      flavors: 'cereja negra, ameixa, violeta, lilás, sálvia',
      aromas_wf: ['Cereja negra', 'Ameixa', 'Violeta', 'Lilás', 'Sálvia'], aromas_wiki: ['Banana', 'Couro'] },

    { name: 'Tannat', color: 'tinta', wiki: 'Tannat', wf: 'tannat',
      origin: 'Sudoeste da França.',
      synonyms: ['Tanat', 'Moustrou', 'Harriague'],
      main_countries: 'França, Uruguai, Argentina, Brasil, Austrália, Peru, África do Sul, Itália, EUA',
      main_regions: 'Madiran (França); Uruguai; Paso Robles e Santa Cruz Mountains (Califórnia)',
      description: 'Na França: estrutura firme e tânica, framboesa e álcool alto. No Uruguai: mais leve e menos tânico, com amora. Também vira rosé. Serviço: 15–20 °C. Guarda: 10+ anos.',
      profile: P('seco', 'encorpado', 'alto', 'media', 'medio..alto'),
      flavors: 'cassis, ameixa, alcaçuz, fumaça, cardamomo',
      aromas_wf: ['Cassis', 'Ameixa', 'Alcaçuz', 'Fumaça'], aromas_wiki: ['Framboesa', 'Amora'] },

    { name: 'Carignan', color: 'tinta', wiki: 'Carignan', wf: 'carignan',
      origin: 'Cariñena (Aragão, Espanha).',
      synonyms: ['Cariñena', 'Mazuelo', 'Samsó', 'Carignane', 'Carignano', 'Bovale Grande'],
      main_countries: 'França, Espanha, Itália',
      main_regions: 'Languedoc; Priorat e Rioja (Mazuelo); Sardenha',
      ripening: 'Brotação e maturação tardias.', vigor: 'Muito vigorosa (cerca de 200 hl/ha sem controle).',
      disease_sensitivity: 'Podridão, oídio, míldio e traças da uva.',
      climate: 'Mediterrâneo quente ou muito quente para amadurecer bem.',
      description: 'Acidez, taninos e adstringência altos; muito usada para dar cor aos cortes. Serviço: 15–20 °C. Guarda: 5–10 anos.',
      profile: P('seco', 'medio', 'medio', 'media+', 'medio..alto'),
      flavors: 'cranberry seca, framboesa, folha de tabaco, especiarias doces, carne curada',
      aromas_wf: ['Cranberry', 'Framboesa', 'Tabaco', 'Carne'], aromas_wiki: [] },

    // ============================== BRANCAS ==============================
    { name: 'Chardonnay', color: 'branca', wiki: 'Chardonnay', wf: 'chardonnay',
      origin: 'Borgonha (centro-leste da França).',
      synonyms: ['Beaunois', 'Aubaine', 'Moreau Blanc', 'Auvernat Blanc', 'Gentil Blanc'],
      main_countries: 'França, EUA, Austrália, Nova Zelândia, Canadá, Itália, África do Sul',
      main_regions: 'Chablis, Borgonha, Champagne, Napa Valley, Sonoma, Hunter Valley, Adelaide Hills, Marlborough',
      ripening: 'Brota cedo (cerca de uma semana depois do Pinot Noir) e amadurece cedo.',
      vigor: 'Muito vigorosa; acima de 80 hl/ha a qualidade cai.', skin_thickness: 'Casca verde que fica verde-dourada ao amadurecer',
      disease_sensitivity: 'Bagoinha (millerandage), oídio, geada, desavinho.',
      climate: 'Frio: vinhos magros, crocantes, de acidez alta; médio/quente: mel e frutas tropicais.',
      soils: 'Giz e calcário; também argila.',
      description: 'Sem carvalho: maçã verde e notas minerais. A fermentação malolática dá textura amanteigada; o carvalho acrescenta baunilha, caramelo e especiarias. Historicamente confundida com a Pinot Blanc. Serviço: 7–12 °C. Guarda: 5–10 anos.',
      profile: P('seco', 'medio', 'baixo', 'media', 'medio..alto'),
      flavors: 'limão, maçã amarela, manteiga, baunilha, abacaxi',
      aromas_wf: ['Limão', 'Manteiga', 'Baunilha', 'Abacaxi'], aromas_wiki: ['Maçã verde', 'Caramelo', 'Mel'] },

    { name: 'Sauvignon Blanc', color: 'branca', wiki: 'Sauvignon_blanc', wf: 'sauvignon-blanc',
      origin: 'Vale do Loire (França).',
      synonyms: ['Sauvignon Jaune', 'Blanc Fumé', 'Fumé Blanc', 'Muskat-Silvaner'],
      main_countries: 'França, Nova Zelândia, Chile, África do Sul, Austrália, Argentina, EUA',
      main_regions: 'Loire (Sancerre, Pouilly-Fumé), Bordeaux, Marlborough, Adelaide Hills, Valparaíso (Chile)',
      ripening: 'Costuma brotar tarde e amadurecer cedo.', vigor: 'Rendimentos menores são incentivados nas regiões de qualidade.',
      disease_sensitivity: 'Oídio, podridão negra, botrytis.', climate: 'Frio a moderado; sofre com calor excessivo.',
      soils: 'Giz, marga, cascalho, sílex, calcário.',
      description: 'Acidez alta; seco, crocante e refrescante; de herbáceo (grama) a tropical conforme o clima — metoxipirazinas e tióis. No Chile, cuidado com a Sauvignonasse, outra variedade. Serviço: 7–12 °C. Guarda: 3–5 anos.',
      profile: P('seco', 'medio-', 'baixo', 'alta', 'medio'),
      flavors: 'groselha espinhosa, melão, grapefruit, pêssego branco, maracujá',
      aromas_wf: ['Groselha espinhosa', 'Melão', 'Grapefruit', 'Pêssego', 'Maracujá'], aromas_wiki: ['Grama cortada'] },

    { name: 'Riesling', color: 'branca', wiki: 'Riesling', wf: 'riesling',
      origin: 'Vale do Reno (oeste da Alemanha); registrada na Alsácia em 1470 e na Áustria por volta de 1700.',
      synonyms: ['Rheinriesling', 'Johannisberger', 'Rhine Riesling', 'Riesling Renano'],
      main_countries: 'Alemanha (40% da produção mundial), França (Alsácia), Áustria, Austrália, Nova Zelândia, Canadá, EUA',
      main_regions: 'Mosel, Rheingau, Pfalz, Rheinhessen, Nahe; Alsácia; Clare Valley, Eden Valley; Wachau; Finger Lakes, Washington',
      ripening: 'Tardia; o ideal é uma maturação longa e lenta.', climate: 'Regiões frias.', soils: 'Ardósia e argila arenosa.',
      disease_sensitivity: 'Em regiões muito frias, risco de não amadurecer.',
      description: 'Acidez alta, aromática; maçã e frutas de pomar (clima frio), cítricos e pêssego (mais quente); com a idade, "petróleo" (composto TDN). Do seco ao doce; raramente passa por carvalho. Serviço: 3–7 °C. Guarda: 10+ anos.',
      profile: P('seco..doce', 'leve', 'baixo', 'alta', 'baixo'),
      flavors: 'lima, maçã verde, cera de abelha, jasmim, petróleo',
      aromas_wf: ['Lima', 'Maçã verde', 'Cera', 'Jasmim', 'Petróleo / querosene'], aromas_wiki: ['Pêssego'] },

    { name: 'Chenin Blanc', color: 'branca', wiki: 'Chenin_blanc', wf: 'chenin-blanc',
      origin: 'Vale do Loire (França), século IX.',
      synonyms: ['Steen', 'Pineau de la Loire', 'Plant d\'Anjou', 'Gros Chenin'],
      main_countries: 'França, África do Sul, EUA, Austrália, Argentina',
      main_regions: 'Loire; Paarl, Swartland; Clarksburg; Mendoza',
      ripening: 'Brota cedo; maturação média a tardia.', vigor: 'Naturalmente vigorosa, tende à superprodução.',
      bunch_size: 'Cônico, com asa', berry_size: 'Cerca de 16 × 14 mm, ~1,8 g',
      disease_sensitivity: 'Podridão do cacho, queimadura de sol, geada, oídio.',
      soils: 'Argila favorece vinhos doces botritizados; areia, estilos leves; sílex, mineralidade; calcário aumenta a acidez; xisto adianta a maturação.',
      description: 'A acidez alta é a marca. Do seco ao doce, espumante e de sobremesa (guarda de mais de 100 anos). Aromas de ameixa-rainha-cláudia, angélica, mel e notas minerais. Chamada de "a resposta francesa ao Riesling alemão". Serviço: 7–12 °C. Guarda: 10+ anos.',
      profile: P('seco..doce', 'medio-', 'baixo', 'alta', 'medio'),
      flavors: 'marmelo, maçã amarela, pera, camomila, mel',
      aromas_wf: ['Marmelo', 'Pera', 'Camomila', 'Mel'], aromas_wiki: [] },

    { name: 'Pinot Gris', color: 'rosada', wiki: 'Pinot_gris', wf: 'pinot-gris',
      origin: 'Mutação de cor do Pinot Noir (perfil de DNA praticamente igual).',
      synonyms: ['Pinot Grigio', 'Grauburgunder', 'Ruländer', 'Szürkebarát', 'Tokay d\'Alsace', 'Pinot Beurot'],
      main_countries: 'França, Itália, Alemanha, Áustria, Hungria, Nova Zelândia, EUA, Austrália',
      main_regions: 'Alsácia, Friuli-Venezia Giulia, Alto Adige, Oregon, Baden, Badacsony, Marlborough, Tasmânia',
      vigor: 'Historicamente, rendimentos baixos e irregulares.', skin_thickness: 'Casca rosa-acinzentada (do azul-acinzentado ao marrom-rosado)',
      bunch_size: 'Pequeno, em forma de pinha', climate: 'Climas frios.', soils: 'Vulcânicos (Alsácia).',
      description: 'Estilo italiano (Pinot Grigio): leve, magro, de acidez crocante. Estilo alsaciano (Pinot Gris): médio a encorpado, especiado, com potencial de guarda. Serviço: 7–12 °C. Guarda: 3–5 anos.',
      profile: P('seco', 'medio-', 'baixo', 'media+', 'medio'),
      flavors: 'pêssego branco, raspas de limão, melão cantalupo, amêndoa verde, cascalho',
      aromas_wf: ['Pêssego', 'Limão', 'Melão', 'Amêndoa'], aromas_wiki: [] },

    { name: 'Gewürztraminer', color: 'rosada', wiki: 'Gew%C3%BCrztraminer', wf: 'gewurztraminer',
      origin: 'Mutação aromática do Savagnin (Traminer), originária de Tramin, no Alto Adige (Itália).',
      synonyms: ['Traminer Musqué', 'Savagnin Rose', 'Roter Traminer', 'Traminec', 'Clevener'],
      main_countries: 'França (Alsácia), Alemanha, Itália, Áustria, Nova Zelândia, EUA, Canadá, Austrália',
      main_regions: 'Alsácia, Trentino-Alto Adige, Alemanha, Okanagan (Canadá), Califórnia, Tasmânia, Marlborough',
      skin_thickness: 'Casca rosa a vermelha (uva de vinho branco)',
      disease_sensitivity: 'Muito sensível, sobretudo a viroses e à podridão em clima úmido.',
      climate: 'Climas frios.', soils: 'Silicosos finos realçam o lado especiado; dolomíticos dão vinhos mais florais e leves.',
      description: 'Muitas vezes meio seco, com açúcar natural alto; buquê exuberante de lichia, rosa, maracujá e flores — Gewürztraminer e lichia compartilham os mesmos compostos aromáticos. Serviço: 6–8 °C. Guarda: 3–5 anos (os melhores, 10+).',
      profile: P('meio_seco', 'medio', 'baixo', 'baixa', 'medio..alto'),
      flavors: 'lichia, rosa, grapefruit, tangerina, gengibre',
      aromas_wf: ['Lichia', 'Rosa', 'Grapefruit', 'Tangerina', 'Gengibre'], aromas_wiki: ['Maracujá'] },

    { name: 'Viognier', color: 'branca', wiki: 'Viognier', wf: 'viognier',
      origin: 'França.',
      synonyms: ['Vionnier'],
      main_countries: 'França, EUA, Austrália, Nova Zelândia, África do Sul, Chile, Argentina',
      main_regions: 'Condrieu, Château-Grillet, Côte-Rôtie (França); Central Coast (Califórnia); Eden Valley (Austrália)',
      ripening: 'Amadurece antes da Syrah; precisa de estação longa e quente.', vigor: 'Rendimentos baixos e imprevisíveis.',
      disease_sensitivity: 'Propensa ao oídio.', climate: 'Quente; clima mediterrâneo.', soils: 'Granito; franco e argila (Eden Valley).',
      description: 'Acidez baixa, encorpado e untuoso; pêssego, pera, violeta e mineral; cerca de 13% de álcool; quase sempre seco. Parente de Freisa e Nebbiolo (DNA, 2004). Comparado ao Chardonnay pelo corpo, mas com mais aromas naturais. Serviço: 7–12 °C. Guarda: 3–5 anos.',
      profile: P('seco', 'encorpado', 'baixo', 'media-', 'medio..alto'),
      flavors: 'tangerina, pêssego, manga, madressilva, rosa',
      aromas_wf: ['Tangerina', 'Pêssego', 'Manga', 'Madressilva', 'Rosa'], aromas_wiki: ['Pera', 'Violeta'] },

    { name: 'Sémillon', color: 'branca', wiki: 'S%C3%A9millon', wf: 'semillon',
      origin: 'Oeste da França (Bordeaux).',
      synonyms: ['Hunter River Riesling', 'Groendruif', 'Wyndruif', 'Colombier', 'Blanc Doux'],
      main_countries: 'França, Austrália, Chile, Argentina, África do Sul, Nova Zelândia',
      main_regions: 'Sauternes, Barsac, Bordeaux; Hunter Valley (Austrália)',
      ripening: 'Precoce.', vigor: 'Vigorosa (6–8 t por acre).', skin_thickness: 'Fina, dourada',
      disease_sensitivity: 'Sensível à botrytis (podridão nobre); fora isso, razoavelmente resistente.',
      climate: 'Dias ensolarados e noites frias; risco de queimadura em clima quente.',
      description: 'Acidez baixa, vinho "pesado", de textura oleosa; envelhece bem. O Hunter Semillon envelhecido fica amarelo-manteiga, com notas de torrada e mel. Base dos Sauternes, com Sauvignon Blanc e Muscadelle. Serviço: 7–12 °C. Guarda: 5–10 anos (secos); Sauternes, 10–50+.',
      profile: P('seco', 'medio', 'baixo', 'media', 'medio..alto'),
      flavors: 'limão, cera de abelha, pêssego, camomila, salino',
      aromas_wf: ['Limão', 'Cera', 'Pêssego', 'Camomila', 'Salino'], aromas_wiki: ['Tostado', 'Mel'] },

    { name: 'Albariño', color: 'branca', wiki: 'Albari%C3%B1o', wf: 'albarino',
      origin: 'Galiza (Espanha) e noroeste de Portugal.',
      synonyms: ['Alvarinho', 'Albelleiro', 'Galego', 'Cainho Branco'],
      main_countries: 'Espanha, Portugal, EUA, Uruguai, Austrália',
      main_regions: 'Rías Baixas (Espanha); Vinho Verde — Monção e Melgaço (Portugal)',
      vigor: 'Rendimentos altos.', skin_thickness: 'Grossa', bunch_size: 'Grande', climate: 'Responde bem a calor e umidade.',
      description: 'Acidez alta, álcool de 11,5–12,5%, corpo leve; aroma botânico com fundo cítrico, lembrando damasco e pêssego; pode ter leve amargor final. Na Austrália, vinhas vendidas como Albariño eram na verdade Savagnin. Serviço: 3–7 °C. Guarda: 3–5 anos.',
      profile: P('seco', 'leve', 'baixo', 'alta', 'medio'),
      flavors: 'raspas de limão, grapefruit, melão, nectarina, salino',
      aromas_wf: ['Limão', 'Grapefruit', 'Melão', 'Nectarina', 'Salino'], aromas_wiki: ['Damasco', 'Pêssego'] },

    { name: 'Grüner Veltliner', color: 'branca', wiki: 'Gr%C3%BCner_Veltliner', wf: 'gruner-veltliner',
      origin: 'Áustria (provavelmente autóctone).',
      synonyms: ['Weissgipfler', 'Grüner Muskateller', 'Veltlínské Zelené', 'Zöld Veltelini'],
      main_countries: 'Áustria, República Tcheca, Eslováquia, Hungria',
      main_regions: 'Weinviertel, Wachau, Kamptal, Kremstal, Traisental, Leithaberg',
      ripening: 'Maturação média (meados a fim de outubro no hemisfério norte).',
      vigor: 'Muito fértil, rendimento alto (até 100 hl/ha no Weinviertel).', skin_thickness: 'Casca verde profunda',
      berry_size: 'Pequena', bunch_size: 'Longo e compacto', disease_sensitivity: 'Míldio, oídio, ácaros.',
      climate: 'Regiões frias.', soils: 'Com muito loess.',
      description: 'Seco, mineral, de acidez crocante; nota característica de pimenta branca, lentilha e aipo; os mais encorpados ganham peso de mel. Serviço: 7–12 °C. Guarda: 10+ anos.',
      profile: P('seco', 'medio-', 'baixo', 'alta', 'medio'),
      flavors: 'carambola, groselha espinhosa, vagem, pimenta branca, cascalho',
      aromas_wf: ['Carambola', 'Groselha espinhosa', 'Pimenta branca'], aromas_wiki: ['Mel'] },

    { name: 'Muscat Blanc à Petits Grains', color: 'branca', wiki: 'Muscat_Blanc_%C3%A0_Petits_Grains', wf: 'muscat-blanc',
      origin: 'Grécia.',
      synonyms: ['Moscato Bianco', 'Moscato Canelli', 'Muscat de Frontignan', 'Gelber Muskateller', 'Moscatel de Grano Menudo'],
      main_countries: 'Itália, França, Espanha, Grécia, Austrália, África do Sul',
      main_regions: "Piemonte (Asti, Moscato d'Asti), Samos, Alsácia, Muscat de Beaumes-de-Venise, Castilla-La Mancha",
      ripening: 'Brota cedo e amadurece tarde; precisa de estação longa.', vigor: 'Rendimentos baixos.',
      skin_thickness: 'Casca branca (há linhagens rosadas e marrom-avermelhadas na Austrália e na África do Sul)',
      berry_size: 'Pequena', bunch_size: 'Compacto',
      disease_sensitivity: 'Míldio, traça da uva, enrolamento da folha, oídio, podridão cinzenta.',
      description: "Brancos secos aromáticos, vinhos de sobremesa, fortificados e frisantes (Moscato d'Asti). Não confundir com a Muscat of Alexandria nem com a Muscat Ottonel. Serviço: 7–12 °C. Guarda: 3–5 anos.",
      profile: P('meio_seco', 'leve', 'baixo', 'media+', 'baixo'),
      flavors: 'flor de laranjeira, limão-siciliano, tangerina, pera, madressilva',
      aromas_wf: ['Flor de laranjeira', 'Limão', 'Tangerina', 'Pera', 'Madressilva'], aromas_wiki: [] },

    { name: 'Vermentino', color: 'branca', wiki: 'Vermentino', wf: 'vermentino',
      origin: 'Itália.',
      synonyms: ['Rolle', 'Pigato', 'Favorita', 'Formentino'],
      main_countries: 'Itália, França, EUA',
      main_regions: 'Sardenha (Vermentino di Gallura DOCG), Ligúria, Toscana, Piemonte (Favorita), Languedoc-Roussillon, Provence (Bellet), Córsega',
      skin_thickness: 'Casca clara, amarelo-âmbar', bunch_size: 'Piramidal',
      climate: 'Mediterrâneo; vinhas muitas vezes em encostas voltadas para o mar.',
      description: 'Dá brancos secos, doces e espumantes. Serviço: 7–12 °C. Guarda: 3–5 anos.',
      profile: P('seco', 'medio-', 'baixo', 'media+', 'medio'),
      flavors: 'lima, grapefruit, maçã verde, amêndoa, narciso',
      aromas_wf: ['Lima', 'Grapefruit', 'Maçã verde', 'Amêndoa'], aromas_wiki: [] },

    { name: 'Garganega', color: 'branca', wiki: 'Garganega', wf: 'garganega',
      origin: 'Províncias de Verona e Vicenza (Itália).',
      synonyms: ['Grecanico Dorato', 'Garganega Veronese'],
      main_countries: 'Itália',
      main_regions: 'Soave (principal), Gambellara, Bianco di Custoza, Colli Berici, Colli Euganei; Sicília (como Grecanico Dorato)',
      ripening: 'Tende a amadurecer tarde.', vigor: 'Muito vigorosa; rendimentos excessivos na planície dão vinhos ralos e neutros.',
      description: 'Acidez alta; delicado, com limão, amêndoa e notas especiadas no Soave Classico. O Recioto di Soave (doce) melhora por uma década ou mais. Idêntica ao Grecanico Dorato da Sicília; aparentada com Trebbiano Toscano, Albana e Catarratto. Serviço: 7–12 °C. Guarda: 5–10 anos.',
      profile: P('seco', 'medio-', 'baixo', 'media+', 'medio'),
      flavors: 'pêssego, melão, tangerina, manjerona, salino',
      aromas_wf: ['Pêssego', 'Melão', 'Tangerina', 'Salino'], aromas_wiki: ['Limão', 'Amêndoa'] },

    { name: 'Torrontés', color: 'branca', wiki: 'Torront%C3%A9s', wf: 'torrontes',
      origin: 'Argentina. Há três Torrontés diferentes: Riojano (o mais plantado), Sanjuanino e Mendocino.',
      synonyms: ['Torrontés Riojano', 'Torrontel'],
      main_countries: 'Argentina, Chile, Bolívia',
      main_regions: 'La Rioja, Salta (Cafayate, acima de 1.600 m), San Juan, Río Negro; Vales Calchaquíes',
      vigor: 'Muito produtiva.', skin_thickness: 'Casca amarelo-clara a amarelo-escura',
      bunch_size: 'Riojano e Sanjuanino: grandes e soltos; Mendocino: menores e compactos',
      description: 'Vinhos frescos e aromáticos, de acidez moderada, com pêssego e damasco marcantes; lembram Muscat. Para beber jovem. Serviço: 3–7 °C. Guarda: 3–5 anos.',
      profile: P('seco', 'medio-', 'baixo', 'media', 'medio'),
      flavors: 'limão-siciliano, pêssego, pétala de rosa, gerânio, raspas cítricas',
      aromas_wf: ['Limão', 'Pêssego', 'Rosa', 'Gerânio'], aromas_wiki: ['Damasco'] },

    { name: 'Verdejo', color: 'branca', wiki: 'Verdejo', wf: 'verdejo',
      origin: 'Norte da África; chegou a Rueda (Espanha) por volta do século XI, talvez com os moçárabes.',
      synonyms: [],
      main_countries: 'Espanha', main_regions: 'Rueda (principal); Toro, Tierra del Vino',
      disease_sensitivity: 'Propensa à oxidação (daí o estilo oxidativo tradicional).',
      climate: 'Quente (28–30 °C durante o dia em setembro).',
      description: 'Aromático e macio. Regras: mínimo de 50% para o rótulo "Rueda" e de 85% para "Rueda Verdejo". Não é a Verdelho. Serviço: 3–7 °C. Guarda: 3–5 anos.',
      profile: P('seco', 'leve', 'baixo', 'media+', 'medio'),
      flavors: 'lima, melão, casca de grapefruit, erva-doce, pêssego branco',
      aromas_wf: ['Lima', 'Melão', 'Grapefruit', 'Erva-doce', 'Pêssego'], aromas_wiki: [] }
  ];

  // Relações. parent_of: [pai/mãe, filha, artigo-fonte]. confused_with: [a, b, artigo-fonte, como diferenciar].
  var relations = [
    ['parent_of', 'Cabernet Franc', 'Cabernet Sauvignon', 'Cabernet_Sauvignon'],
    ['parent_of', 'Sauvignon Blanc', 'Cabernet Sauvignon', 'Cabernet_Sauvignon'],
    ['parent_of', 'Cabernet Franc', 'Merlot', 'Merlot'],
    ['parent_of', 'Magdeleine Noire des Charentes', 'Merlot', 'Merlot'],
    ['parent_of', 'Cabernet Franc', 'Carménère', 'Carmenere'],
    ['parent_of', 'Trousseau', 'Carménère', 'Carmenere'],
    ['parent_of', 'Cabernet Sauvignon', 'Marselan', 'Grenache'],
    ['parent_of', 'Grenache', 'Marselan', 'Grenache'],
    ['parent_of', 'Pinot Noir', 'Chardonnay', 'Chardonnay'],
    ['parent_of', 'Gouais Blanc', 'Chardonnay', 'Chardonnay'],
    ['parent_of', 'Pinot Noir', 'Gamay', 'Pinot_noir'],
    ['parent_of', 'Gouais Blanc', 'Gamay', 'Pinot_noir'],
    ['parent_of', 'Pinot Noir', 'Aligoté', 'Pinot_noir'],
    ['parent_of', 'Gouais Blanc', 'Aligoté', 'Pinot_noir'],
    ['parent_of', 'Gouais Blanc', 'Melon de Bourgogne', 'Pinot_noir'],
    ['parent_of', 'Pinot Noir', 'Auxerrois Blanc', 'Pinot_noir'],
    ['parent_of', 'Gouais Blanc', 'Auxerrois Blanc', 'Pinot_noir'],
    ['parent_of', 'Pinot Noir', 'Pinotage', 'Pinotage'],
    ['parent_of', 'Cinsaut', 'Pinotage', 'Pinotage'],
    ['parent_of', 'Dureza', 'Syrah', 'Syrah'],
    ['parent_of', 'Mondeuse Blanche', 'Syrah', 'Syrah'],
    ['parent_of', 'Syrah', 'Petite Sirah', 'Syrah'],
    ['parent_of', 'Peloursin', 'Petite Sirah', 'Syrah'],
    ['parent_of', 'Benedicto', 'Tempranillo', 'Tempranillo'],
    ['parent_of', 'Albillo Mayor', 'Tempranillo', 'Tempranillo'],
    ['parent_of', 'Primitivo', 'Plavac Mali', 'Zinfandel'],
    ['parent_of', 'Dobričić', 'Plavac Mali', 'Zinfandel'],
    ['parent_of', 'Chatus', 'Dolcetto', 'Dolcetto'],
    ['parent_of', 'Corvina', 'Rondinella', 'Corvina'],
    ['parent_of', 'Gouais Blanc', 'Riesling', 'Riesling'],
    ['parent_of', 'Riesling', 'Müller-Thurgau', 'Riesling'],
    ['parent_of', 'Savagnin', 'Chenin Blanc', 'Chenin_blanc'],
    ['parent_of', 'Savagnin', 'Grüner Veltliner', 'Gr%C3%BCner_Veltliner'],
    ['parent_of', 'St. Georgener-Rebe', 'Grüner Veltliner', 'Gr%C3%BCner_Veltliner'],
    ['parent_of', 'Savagnin', 'Verdejo', 'Verdejo'],
    ['parent_of', 'Castellana Blanca', 'Verdejo', 'Verdejo'],
    ['parent_of', 'Listán Prieto', 'Torrontés', 'Torront%C3%A9s'],
    ['parent_of', 'Muscat of Alexandria', 'Torrontés', 'Torront%C3%A9s'],
    ['parent_of', 'Carignan', 'Ruby Cabernet', 'Carignan'],
    ['parent_of', 'Cabernet Sauvignon', 'Ruby Cabernet', 'Carignan'],

    ['confused_with', 'Merlot', 'Carménère', 'Carmenere',
      'No Chile foram plantadas misturadas e confundidas por muito tempo. Na vinha, o verso da folha da Carménère é avermelhado (branco na Merlot); ela brota e amadurece mais tarde. Na taça, a Carménère mostra pimentão e páprica (Wine Folly).'],
    ['confused_with', 'Cabernet Franc', 'Cabernet Sauvignon', 'Cabernet_Franc',
      'O Cabernet Franc é mais claro, mais leve e tem taninos mais baixos que o Cabernet Sauvignon; costuma mostrar framboesa e pimentão, enquanto o Cabernet Sauvignon mostra cassis, cedro e grafite.'],
    ['confused_with', 'Merlot', 'Cabernet Sauvignon', 'Merlot',
      'O Merlot tem casca mais fina, taninos médios e textura macia e aveludada (ameixa, chocolate); o Cabernet Sauvignon é mais tânico e encorpado (cassis, cedro, grafite).'],
    ['confused_with', 'Gamay', 'Pinot Noir', 'Gamay',
      'Pelos perfis da Wine Folly, o Gamay tem corpo mais leve, praticamente sem taninos e álcool mais baixo (10–11,5%) que o Pinot Noir (corpo médio, 12–14%). Os dois têm acidez média-alta e frutas vermelhas.'],
    ['confused_with', 'Aglianico', 'Nebbiolo', 'Aglianico',
      'O Aglianico é chamado de "Barolo do Sul": os dois têm taninos e acidez altos. O Aglianico tem cor granada profunda e fruta negra (cereja negra, ameixa); o Nebbiolo tem cor clara com aro alaranjado e rosas e alcatrão.'],
    ['confused_with', "Nero d'Avola", 'Syrah', 'Nero_d%27Avola',
      "O Nero d'Avola é comparado aos Shiraz do Novo Mundo: fruta negra e notas apimentadas."],
    ['confused_with', 'Petite Sirah', 'Syrah', 'Syrah',
      'São variedades diferentes: a Petite Sirah é filha da Syrah com a Peloursin.'],
    ['confused_with', 'Montepulciano', 'Sangiovese', 'Montepulciano_(grape)',
      'Confusão de nomes: o Vino Nobile di Montepulciano (Toscana) é feito de Sangiovese; a uva Montepulciano é do Abruzzo e já foi considerada sinônimo de Sangiovese.'],
    ['confused_with', 'Corvina', 'Corvinone', 'Corvina',
      'Foram confundidas por muito tempo; o DNA mostra que são variedades diferentes.'],
    ['confused_with', 'Viognier', 'Chardonnay', 'Viognier',
      'Corpo parecido, mas a Viognier tem mais aromas naturais (pêssego, pera, flores) e acidez mais baixa.'],
    ['confused_with', 'Chenin Blanc', 'Riesling', 'Chenin_blanc',
      'Os dois têm acidez alta e vão do seco ao doce. A Chenin mostra marmelo, pera, camomila e mel; o Riesling, lima, maçã verde, jasmim e, com a idade, petróleo (Wine Folly).'],
    ['confused_with', 'Albariño', 'Savagnin', 'Albari%C3%B1o',
      'Na Austrália, vinhas compradas como Albariño eram na verdade Savagnin (erro de identificação).'],
    ['confused_with', 'Torrontés', 'Gewürztraminer', 'Torront%C3%A9s',
      'Os dois são muito aromáticos e florais (rosa). Pela Wine Folly, o Gewürztraminer é meio seco, com lichia e gengibre e acidez baixa; o Torrontés é seco, com pêssego, limão e gerânio.'],
    ['confused_with', 'Grüner Veltliner', 'Riesling', 'Gr%C3%BCner_Veltliner',
      'Comparados pela mineralidade. O Grüner Veltliner tem a nota típica de pimenta branca (e lentilha, aipo); o Riesling é mais aromático, com lima, maçã verde e, com a idade, petróleo.']
  ];

  // ============================== v2 — ITALIANAS ==============================
  var GRAPES_V2 = [
    { name: 'Trebbiano Toscano', color: 'branca', wiki: 'Trebbiano', wf: '',
      origin: 'Itália.',
      synonyms: ['Ugni Blanc', 'Procanico', 'White Hermitage', 'Clairette Ronde'],
      main_countries: 'Itália, França, Austrália',
      main_regions: "Orvieto (Úmbria), Trebbiano d'Abruzzo; na França, base do Cognac e do Armagnac (como Ugni Blanc)",
      vigor: 'Vigorosa e de alto rendimento.', skin_thickness: 'Resistente, com suco amarelo e ácido', bunch_size: 'Longo e cilíndrico',
      description: 'Acidez alta; fresco e frutado, mas não envelhece muito. Essencial para Cognac e Armagnac e usado no aceto balsâmico. Pode ser confundido com o Verdicchio.',
      profile: P('', '', '', 'alta', ''), aromas_wf: [], aromas_wiki: [] },

    { name: 'Fiano', color: 'branca', wiki: 'Fiano_(grape)', wf: 'fiano',
      origin: 'Itália (Campânia).',
      synonyms: ['Apiano', 'Fiore Mendillo', 'Latina Bianca'],
      main_countries: 'Itália, Austrália, Argentina, EUA',
      main_regions: 'Fiano di Avellino DOCG (Campânia); Sicília; McLaren Vale, Clare Valley, Hunter Valley (Austrália)',
      vigor: 'Rendimentos relativamente baixos.', skin_thickness: 'Grossa', berry_size: 'Pequena, com pouquíssimo suco',
      description: 'Palha claro; sabor intenso com mel, especiarias e flores; desenvolve notas de avelã; tem potencial de guarda. Serviço: 7–12 °C. Guarda: 5–10 anos.',
      profile: P('seco', 'medio-', 'baixo', 'media', 'medio'),
      flavors: 'melão, pera asiática, avelã, casca de laranja, pinho',
      aromas_wf: ['Melão', 'Pera', 'Frutos secos (nozes)', 'Casca de laranja'], aromas_wiki: ['Mel'] },

    { name: 'Greco', color: 'branca', wiki: 'Greco_(grape)', wf: '',
      origin: 'Possivelmente levada ao sul da Itália por colonos gregos há mais de 2.500 anos.',
      synonyms: ['Greco Bianco', 'Greco di Tufo', 'Greco del Vesuvio'],
      main_countries: 'Itália', main_regions: 'Greco di Tufo DOCG (Campânia); Greco di Bianco (Calábria)',
      ripening: 'Amadurece muito tarde.', bunch_size: 'Com asas características; bagas cinza-douradas após o pintor',
      disease_sensitivity: 'Míldio e oídio.', soils: 'Solos derivados de tufo vulcânico (Greco di Tufo).',
      description: 'Aromático, com pêssego e notas de folhagem; ganha notas herbáceas com a idade; "vagamente parecido com o Viognier".',
      profile: P('', '', '', '', ''), aromas_wf: [], aromas_wiki: ['Pêssego'] },

    { name: 'Falanghina', color: 'branca', wiki: 'Falanghina', wf: 'falanghina',
      origin: 'Itália (Campânia); talvez a base do antigo Falernum. O nome pode vir do latim "falangae" (estacas da vinha).',
      synonyms: ['Falernina', 'Falanchina'],
      main_countries: 'Itália', main_regions: 'Campânia (norte de Nápoles): Falanghina del Sannio, Campi Flegrei',
      description: 'Variedade antiga, de muito caráter; clássica com frutos do mar no sul da Itália. Serviço: 7–12 °C. Guarda: 3–5 anos.',
      profile: P('seco', 'medio-', 'baixo', 'media', 'medio'),
      flavors: 'limão, flor cítrica, pêssego, mel, amêndoa',
      aromas_wf: ['Limão', 'Flor de laranjeira', 'Pêssego', 'Mel', 'Amêndoa'], aromas_wiki: [] },

    { name: 'Negroamaro', color: 'tinta', wiki: 'Negroamaro', wf: 'negroamaro',
      origin: 'Sul da Itália (Puglia).',
      synonyms: ['Negramaro', 'Nero Amaro'],
      main_countries: 'Itália',
      main_regions: 'Puglia (Salento): Salice Salentino, Brindisi, Copertino, Leverano, Squinzano, Nardò, Alezio',
      ripening: 'Meia estação (fim de setembro a início de outubro).', vigor: 'Vigorosa e de alto rendimento.',
      skin_thickness: 'Grossa', berry_size: 'Preto-violácea, oval, média a grande', bunch_size: 'Cerca de 300–350 g',
      climate: 'Verões quentes; boa resistência à seca.', soils: 'Calcários; adapta-se com facilidade.',
      description: 'Cor profunda; caráter rústico, que combina perfume com um amargor terroso. Serviço: 15–20 °C. Guarda: 5–10 anos.',
      profile: P('seco', 'medio+', 'medio+', 'media', 'medio..alto'),
      flavors: 'cereja negra, ameixa preta, amora, ameixa seca, tomilho seco',
      aromas_wf: ['Cereja negra', 'Ameixa preta', 'Amora', 'Ameixa seca', 'Tomilho'], aromas_wiki: [] },

    { name: 'Lambrusco', color: 'tinta', wiki: 'Lambrusco', wf: 'lambrusco',
      origin: 'Emília-Romanha e Lombardia; família de variedades cultivada desde os etruscos. Principais: Grasparossa, Salamino, Sorbara, Maestri, Marani, Montericco.',
      synonyms: [],
      main_countries: 'Itália; também Austrália e Argentina',
      main_regions: 'Lambrusco di Sorbara, Lambrusco Grasparossa di Castelvetro, Lambrusco Salamino di Santa Croce, Reggiano, Colli di Parma, Modena, Lambrusco Mantovano',
      vigor: 'Muito produtiva.',
      description: 'Sobretudo frisante (método Charmat), secco, amabile ou dolce; acidez alta; frutas vermelhas e morango, com leve final amargo nos secos; corpo de leve a pleno conforme a variedade. Serviço: 7–12 °C. Guarda: 1–3 anos.',
      profile: P('seco..doce', 'medio-', 'medio', 'media+', 'baixo..medio'),
      flavors: 'morango, amora, ruibarbo, hibisco, terra de vaso',
      aromas_wf: ['Morango', 'Amora', 'Terra molhada'], aromas_wiki: [] },

    { name: 'Friulano', color: 'branca', wiki: 'Sauvignonasse', wf: 'friulano',
      origin: 'Itália (Vêneto); cultivada no Friuli desde 1600. O nome "Tocai" é proibido na UE desde 2007.',
      synonyms: ['Sauvignonasse', 'Tocai Friulano', 'Sauvignon Vert'],
      main_countries: 'Itália, Eslovênia, Chile, Argentina',
      main_regions: 'Friuli-Venezia Giulia (Colli Orientali, Collio, Grave, Isonzo); Goriška Brda (Eslovênia)',
      ripening: 'Brotação tardia.', vigor: 'Rendimentos altos, que precisam de controle.', disease_sensitivity: 'Muito sensível a míldio e oídio.',
      description: 'No Friuli: encorpado, acidez moderada, floral e de fruta delicada; no Chile, maçã verde quando jovem. Nos anos 1990 descobriu-se que muitas vinhas chilenas de "Sauvignon Blanc" eram Sauvignonasse. Serviço: 7–12 °C. Guarda: 3–5 anos.',
      profile: P('seco', 'leve', 'baixo', 'alta', 'medio'),
      flavors: 'grapefruit, pera verde, pêssego branco, estragão, cascalho',
      aromas_wf: ['Grapefruit', 'Pera', 'Pêssego'], aromas_wiki: ['Maçã verde'] },

    { name: 'Verdicchio', color: 'branca', wiki: 'Verdicchio', wf: 'verdicchio',
      origin: 'Marche (Itália), documentada desde o século XIV; aparentada com Trebbiano e Greco.',
      synonyms: ['Boschera Bianca', 'Maceratese'],
      main_countries: 'Itália',
      main_regions: 'Marche (Verdicchio dei Castelli di Jesi, Verdicchio di Matelica); Úmbria; Lácio',
      disease_sensitivity: 'Muito sujeita a mutações clonais; sensível ao clima; rendimentos variáveis.',
      description: 'Acidez alta, cítricos (limão) e leve amêndoa amarga; quase incolor; boa base para espumantes. Serviço: 3–7 °C. Guarda: 1–3 anos.',
      profile: P('seco', 'leve', 'baixo', 'media+', 'medio'),
      flavors: 'pêssego, curd de limão, casca de amêndoa, oleoso, salino',
      aromas_wf: ['Pêssego', 'Limão', 'Amêndoa', 'Salino'], aromas_wiki: [] },

    { name: 'Nerello Mascalese', color: 'tinta', wiki: 'Nerello_Mascalese', wf: 'nerello-mascalese',
      origin: 'Sicília; nome da área de Mascali (Catânia). Provavelmente um cruzamento de Sangiovese com outra uva não identificada (não confirmado).',
      synonyms: [],
      main_countries: 'Itália', main_regions: 'Etna DOC (com Nerello Cappuccio); Faro; nordeste da Sicília',
      description: 'Rubi com toques granada; frutas vermelhas; seco, tânico e persistente. A Nerello Cappuccio é outra variedade. Serviço: 12–15 °C. Guarda: 10+ anos.',
      profile: P('seco', 'medio-', 'medio', 'media+', 'medio'),
      flavors: 'cereja seca, raspas de laranja, tomilho seco, pimenta-da-jamaica, cascalho',
      aromas_wf: ['Casca de laranja', 'Tomilho'], aromas_wiki: [] },

    { name: 'Sagrantino', color: 'tinta', wiki: 'Sagrantino', wf: 'sagrantino',
      origin: 'Úmbria (Itália central).',
      synonyms: [],
      main_countries: 'Itália, Austrália, EUA, Brasil', main_regions: 'Montefalco (Montefalco Sagrantino DOCG desde 1992)',
      ripening: 'Floresce e muda de cor cedo, mas precisa de estação longa e quente; colheita no fim de outubro.',
      vigor: 'Vigorosa, resistente a doenças e de baixo rendimento.', skin_thickness: 'Grossa e escura', berry_size: 'Pequena, de sementes grandes',
      bunch_size: 'Pequeno, levemente cônico, com asa', disease_sensitivity: 'Resistente.',
      description: 'Púrpura quase negro; fruta vermelha escura com ameixa, canela e terra; taninos altíssimos — o dobro dos do Cabernet Sauvignon. Tradicionalmente passito (doce); seco desde os anos 1970. Serviço: 15–20 °C. Guarda: 10+ anos.',
      profile: P('seco', 'encorpado', 'alto', 'media+', 'medio..alto'),
      flavors: 'molho de ameixa, alcaçuz, chá preto, azeitona preta, pimenta-do-reino',
      aromas_wf: ['Ameixa', 'Alcaçuz', 'Chá preto', 'Azeitona preta', 'Pimenta-do-reino'], aromas_wiki: ['Canela', 'Terra molhada'] },

    { name: 'Lagrein', color: 'tinta', wiki: 'Lagrein', wf: '',
      origin: 'Vales do Alto Adige (Tirol do Sul); mencionada no século XVII.',
      synonyms: ['Lagarino'],
      main_countries: 'Itália; também Austrália, EUA, Canadá', main_regions: 'Trentino-Alto Adige/Südtirol',
      description: 'Vinhos "de ameixa, terrosos e mastigáveis, escuros e encorpados sem serem pesados, com borda mineral". Acidez alta e muito tânico. Estilos: Lagrein Scuro/Dunkel (tinto) e Lagrein Rosato/Kretzer (rosé). Aparentada com Marzemino, Syrah, Pinot Noir e Dureza.',
      profile: P('', 'encorpado', 'alto', 'alta', ''), aromas_wf: [], aromas_wiki: ['Ameixa'] },

    { name: 'Teroldego', color: 'tinta', wiki: 'Teroldego', wf: '',
      origin: 'Trentino-Alto Adige (nordeste da Itália). Irmã completa da Dureza (mãe da Syrah).',
      synonyms: [],
      main_countries: 'Itália (96%), EUA, Brasil, Austrália', main_regions: 'Teroldego Rotaliano DOC (Campo Rotaliano, Trentino)',
      ripening: 'Última semana de setembro ou primeira de outubro.', soils: 'Planície aluvial (Campo Rotaliano).',
      description: 'Cor escura e arroxeada; aveludado, taninos macios (redondos, não amargos), toque de especiarias; estilo parecido com o do Lagrein.',
      profile: P('', '', '', '', ''), aromas_wf: [], aromas_wiki: [] },

    { name: 'Refosco dal Peduncolo Rosso', color: 'tinta', wiki: 'Refosco', wf: '',
      origin: 'Itália (zona veneziana e Friuli-Venezia Giulia).',
      synonyms: [],
      main_countries: 'Itália, Eslovênia', main_regions: 'Friuli Colli Orientali; Friuli-Venezia Giulia',
      description: 'Violeta profundo, potente e tânico; groselha, frutas silvestres e ameixa, com leve amargor; ganha notas florais após 4–10 anos. Serviço: 16–18 °C. Aparentada com a Marzemino; o DNA mostrou que não é a Mondeuse Noire.',
      profile: P('', '', 'alto', '', ''), aromas_wf: [], aromas_wiki: ['Ameixa'] },

    { name: 'Arneis', color: 'branca', wiki: 'Arneis', wf: 'arneis',
      origin: 'Itália (Piemonte).',
      synonyms: ["Bianchetta d'Alba", 'Nebbiolo Bianco'],
      main_countries: 'Itália, EUA, Austrália, Nova Zelândia', main_regions: 'Roero DOCG, Langhe DOC',
      ripening: 'Tende a sobreamadurecer depois de setembro.', vigor: 'Rendimentos baixos.',
      disease_sensitivity: 'Oídio (clones recentes toleram melhor).',
      soils: 'No Roero, solos calcários e arenosos dão mais acidez; argila arenosa dá perfume "elegante e exótico".',
      description: 'Acidez naturalmente baixa; seco e encorpado; amêndoa, damasco, pêssego, pera e lúpulo. Serviço: 7–12 °C. Guarda: 0–3 anos.',
      profile: P('seco', 'medio', 'baixo', 'media-', 'medio'),
      flavors: 'pêssego, maçã amarela, mel, amêndoa crua, noz-moscada',
      aromas_wf: ['Pêssego', 'Mel', 'Amêndoa', 'Noz-moscada'], aromas_wiki: ['Damasco', 'Pera'] },

    { name: 'Cortese', color: 'branca', wiki: 'Cortese', wf: '',
      origin: 'Itália (Piemonte).',
      synonyms: ['Cortese Bianco', 'Bianca Fernanda'],
      main_countries: 'Itália',
      main_regions: "Gavi / Cortese di Gavi DOCG; Colli Tortonesi e Cortese dell'Alto Monferrato; Oltrepò Pavese; Garda; Bianco di Custoza",
      vigor: 'Produz colheitas grandes.', disease_sensitivity: 'Resistente a doenças.',
      climate: 'Tem dificuldade de amadurecer nas zonas mais frias de Tortona e do Monferrato.',
      description: 'Acidez moderada, sabores leves e crocantes; corpo médio; lima e ameixa-rainha-cláudia; em safras frias pode ser magro e muito ácido.',
      profile: P('', 'medio', '', 'media', ''), aromas_wf: [], aromas_wiki: ['Lima'] },

    { name: 'Frappato', color: 'tinta', wiki: 'Frappato', wf: '',
      origin: 'Itália (Sicília). Provavelmente um cruzamento de Sangiovese com outra uva não identificada (não confirmado).',
      synonyms: ['Frappato Nero', 'Frappato di Vittoria'],
      main_countries: 'Itália', main_regions: 'Sicília: Cerasuolo di Vittoria DOCG (30–50% Frappato com 50–70% Nero d\'Avola)',
      description: 'Tintos de corpo leve com aroma marcante de uva.',
      profile: P('', 'leve', '', '', ''), aromas_wf: [], aromas_wiki: [] },

    { name: 'Grillo', color: 'branca', wiki: 'Grillo', wf: 'grillo',
      origin: 'Itália; possivelmente levada da Puglia para a Sicília.',
      synonyms: ['Riddu', 'Rossese Bianco'],
      main_countries: 'Itália', main_regions: 'Marsala (principal); Monreale, Alcamo, Contea di Sclafani, Delia Nivolelli; Ilhas Eólias',
      climate: 'Suporta temperaturas altas.',
      description: 'Uva branca siciliana, base tradicional do Marsala e hoje também de brancos secos. Serviço: 7–12 °C. Guarda: 3–5 anos.',
      profile: P('seco', 'medio-', 'baixo', 'media+', 'medio'),
      flavors: 'grapefruit, flor cítrica, tomilho, mineral, salino',
      aromas_wf: ['Grapefruit', 'Flor de laranjeira', 'Tomilho', 'Salino'], aromas_wiki: [] },

    { name: 'Pecorino', color: 'branca', wiki: 'Pecorino_(grape)', wf: '',
      origin: 'Arquata del Tronto (Ascoli Piceno, Marche).',
      synonyms: ['Pecorino di Arquata', 'Arquitano'],
      main_countries: 'Itália', main_regions: 'Marche, Abruzzo, Toscana, Úmbria, Lácio; Offida DOCG, Falerio, Colli Maceratesi, Controguerra',
      ripening: 'Precoce.', vigor: 'Rendimentos naturalmente baixos.', disease_sensitivity: 'Boa resistência a míldio e oídio.',
      description: 'Uva branca do centro da Itália, recuperada nas últimas décadas.',
      profile: P('', '', '', '', ''), aromas_wf: [], aromas_wiki: [] },

    { name: 'Carricante', color: 'branca', wiki: 'Carricante', wf: '',
      origin: 'Sicília (Itália). O nome vem de "caricare" (carregar), pelos rendimentos altos.',
      synonyms: ['Catanese Bianco'],
      main_countries: 'Itália', main_regions: 'Etna DOC (Etna Bianco)',
      ripening: 'Tardia.', vigor: 'Rendimentos altos.',
      climate: 'Alta altitude no Etna (cerca de 950 m na encosta leste e 1.050 m na sul).',
      description: 'Fresco, amarelo-palha, levemente perfumado; acidez total alta e pH baixo; tradicionalmente faz fermentação malolática; cortado com Catarratto e Minella Bianca.',
      profile: P('', '', '', 'alta', ''), aromas_wf: [], aromas_wiki: [] },

    { name: 'Schiava', color: 'tinta', wiki: 'Schiava', wf: '',
      origin: 'Provavelmente norte da Itália (Alto Adige/Trentino), cultivada desde o século XIII. Variedades: Schiava Grossa, Schiava Gentile, Tschaggele.',
      synonyms: ['Vernatsch', 'Trollinger', 'Black Hamburg'],
      main_countries: 'Alemanha, Itália', main_regions: 'Württemberg (Alemanha); Santa Maddalena, Lago di Caldaro, Meranese (Alto Adige)',
      ripening: 'Tardia.', vigor: 'Rendimento alto (Schiava Grossa).', climate: 'Encostas íngremes e ensolaradas.',
      description: 'Tinto leve, de acidez moderada; morango e um leve defumado; para beber jovem; às vezes meio doce em Württemberg.',
      profile: P('', 'leve', '', 'media', ''), aromas_wf: [], aromas_wiki: ['Morango', 'Fumaça'] },

    { name: 'Freisa', color: 'tinta', wiki: 'Freisa', wf: '',
      origin: 'Piemonte (colinas entre Asti e Turim). DNA: relação pai/filho com o Nebbiolo (direção não definida).',
      synonyms: ['Monferrina', 'Fresa', 'Spannina'],
      main_countries: 'Itália; pequenas áreas na Argentina', main_regions: 'Monferrato, Langhe, províncias de Asti, Turim e Biella; Pinerolese',
      ripening: 'Colheita no início de outubro.', vigor: 'Vigorosa e produtiva.',
      disease_sensitivity: 'Muito resistente ao míldio; alguma sensibilidade ao oídio.', climate: 'Encostas bem expostas e ensolaradas.',
      description: 'Tradicionalmente levemente frisante e adocicado; hoje do seco ao doce. Cor relativamente clara com tons roxos; taninos e acidez consideráveis; morango, framboesa e violeta.',
      profile: P('', '', 'medio+..alto', 'media+..alta', ''), aromas_wf: [], aromas_wiki: ['Morango', 'Framboesa', 'Violeta'] },

    { name: 'Ribolla Gialla', color: 'branca', wiki: 'Ribolla_Gialla', wf: 'ribolla-gialla',
      origin: 'Colinas de Gorizia (Collio), documentada em 1289.',
      synonyms: ['Rebula'],
      main_countries: 'Itália, Eslovênia', main_regions: 'Friuli-Venezia Giulia (Collio, Colli Orientali), Brda e Vale do Vipava (Eslovênia)',
      description: 'Branco leve, de acidez alta e notas florais; ganha notas de nozes com a idade. No Collio e no Vipava há versões laranja (maceração com as cascas). Não é a Robola grega (DNA). Serviço: 7–12 °C. Guarda: 3–5 anos.',
      profile: P('seco', 'medio-', 'baixo', 'media+', 'medio'),
      flavors: 'maçã assada, tangerina, cítricos, cera de abelha, tomilho',
      aromas_wf: ['Tangerina', 'Cera', 'Tomilho'], aromas_wiki: ['Frutos secos (nozes)'] },

    { name: 'Grignolino', color: 'tinta', wiki: 'Grignolino', wf: '',
      origin: 'Itália, colinas do Monferrato entre Asti e Casale.',
      synonyms: ['Barbesino'],
      main_countries: 'Itália; pouca produção na Califórnia', main_regions: "Grignolino d'Asti, Grignolino del Monferrato Casalese, Piemonte Grignolino",
      vigor: 'Muito sujeita a bagoinha (millerandage), o que varia o rendimento.',
      description: 'Tintos claros e rosés; aromas muito frutados, acidez e taninos fortes; 11–12% de álcool; notas alpinas, herbáceas ou de framboesa conforme o clone.',
      profile: P('', '', 'alto', 'alta', 'medio'), aromas_wf: [], aromas_wiki: ['Framboesa'] },

    { name: 'Glera', color: 'branca', wiki: 'Glera_(grape)', wf: '',
      origin: 'Origem eslovena e italiana, possivelmente da vila de Prosecco. Renomeada de "Prosecco" para Glera na UE em 2009, para proteger a denominação.',
      synonyms: ['Prosecco', 'Serpina'],
      main_countries: 'Itália', main_regions: 'Vêneto e Friuli: Prosecco DOC; Conegliano Valdobbiadene Prosecco Superiore DOCG; Asolo Prosecco DOCG',
      description: 'Uva bastante neutra, cultivada sobretudo para espumantes e frisantes (Prosecco); também há vinhos tranquilos.',
      profile: P('', '', '', '', ''), aromas_wf: [], aromas_wiki: [] },

    // ============================== v2 — UVAS SECUNDÁRIAS COMPLETADAS ==============================
    { name: 'Pinot Blanc', color: 'branca', wiki: 'Pinot_blanc', wf: '',
      origin: 'Mutação genética do Pinot Noir (um ramo que passa a dar uvas brancas).',
      synonyms: ['Pinot Bianco', 'Weissburgunder', 'Klevner'],
      main_countries: 'França (Alsácia), Alemanha, Áustria, Itália, Hungria, EUA, Canadá', main_regions: 'Alsácia; Alemanha; Áustria; Alto Adige; Oregon; Okanagan',
      description: 'Acidez bastante alta; aromas frutados de maçã, cítricos e flores. Encorpado na Alsácia e no leste europeu; seco ou doce na Alemanha e Áustria. Feito para beber jovem. Confundido com Chardonnay e com Melon de Bourgogne (nos EUA, até os anos 1980).',
      profile: P('', '', '', 'media+..alta', ''), aromas_wf: [], aromas_wiki: ['Maçã verde'] },
    { name: 'Gouais Blanc', color: 'branca', wiki: 'Gouais_blanc', wf: '',
      origin: 'Europa central (provavelmente Áustria/Panônia); muito plantada no centro e nordeste da França na Idade Média.',
      synonyms: ['Weißer Heunisch', 'Heunisch Blanc', 'Gouget Blanc'],
      main_countries: 'Hoje quase extinta; Suíça, Oregon, Austrália',
      description: 'Uva camponesa, de vinhos simples e ácidos. O DNA a revelou ancestral de muitas uvas clássicas: é mãe/pai da Chardonnay e de cerca de 15 outras, como Gamay, Riesling e Melon de Bourgogne.',
      profile: P('', '', '', 'alta', ''), aromas_wf: [], aromas_wiki: [] },
    { name: 'Savagnin', color: 'branca', wiki: 'Savagnin', wf: '',
      origin: 'Alpes; ligada à vila de Tramin (Tirol) por volta do ano 1000.',
      synonyms: ['Traminer', 'Heida', 'Païen', 'Savagnin Blanc'],
      main_countries: 'França, Suíça, Alemanha, Austrália', main_regions: 'Jura (França), famosa pelo vin jaune',
      ripening: 'Muito tardia.',
      description: 'Dá o vin jaune, oxidativo, com véu de leveduras (flor) como o fino de Jerez, e vinhos de sobremesa como o vin de paille. É uma "família de clones": uma mutação aromática deu o Gewürztraminer.',
      profile: P('', '', '', '', ''), aromas_wf: [], aromas_wiki: [] },
    { name: 'Cinsaut', color: 'tinta', wiki: 'Cinsaut', wf: '',
      origin: 'França, possivelmente Hérault.',
      synonyms: ['Cinsault', 'Ottavianello', 'Black Prince', 'Oeillade Noire'],
      main_countries: 'França (Languedoc-Roussillon), Argélia, Marrocos, Tunísia, Líbano, África do Sul, Austrália, Chile, Itália, EUA',
      climate: 'Muito resistente à seca; excelente em clima quente.', vigor: 'Muito produtiva; a qualidade melhora com rendimento controlado.',
      description: 'Tintos leves e frutados, de fruta vermelha crocante e álcool baixo; em cortes, acrescenta maciez e perfume (com Grenache e Carignan). Mãe/pai da Pinotage.',
      profile: P('', 'leve', '', '', 'baixo'), aromas_wf: [], aromas_wiki: [] },
    { name: 'Petite Sirah', color: 'tinta', wiki: 'Petite_Sirah', wf: '',
      origin: 'Montpellier (França), por volta de 1880 (como Durif).',
      synonyms: ['Durif', 'Plant Durif'],
      main_countries: 'Austrália, EUA (Califórnia), França, Israel, Chile, México',
      description: 'Vinhos escuros, quase tinta, de textura firme; acidez relativamente alta; fruta azul e negra, ameixa, mirtilo, notas herbáceas e de pimenta; muito tânico, guarda de 20+ anos. DNA (UC Davis, 1997): Syrah × Peloursin. Mais de 90% das vinhas de "Petite Sirah" da Califórnia são Durif.',
      profile: P('', '', 'alto', '', ''), aromas_wf: [], aromas_wiki: ['Ameixa', 'Mirtilo', 'Pimenta-do-reino'] },
    { name: 'Aligoté', color: 'branca', wiki: 'Aligot%C3%A9', wf: '',
      origin: 'Borgonha (França), registrada no século XVIII.',
      synonyms: ['Blanc de Troyes', 'Plant Gris'],
      main_countries: 'França, Bulgária, Ucrânia, Romênia, Moldávia, Rússia', main_regions: 'Borgonha (Bouzeron, Côte-d\'Or); leste europeu',
      climate: 'Tolera frio.',
      description: 'Acidez alta, com maçã e limão; corpo leve, notas herbáceas; para beber jovem. DNA: Pinot × Gouais Blanc.',
      profile: P('', 'leve', '', 'alta', ''), aromas_wf: [], aromas_wiki: ['Maçã verde', 'Limão'] },
    { name: 'Melon de Bourgogne', color: 'branca', wiki: 'Melon_de_Bourgogne', wf: '',
      origin: 'Borgonha; estabeleceu-se no Loire depois do inverno de 1709.',
      synonyms: ['Muscadet', 'Melon', 'Blanc de Nantes'],
      main_countries: 'França, EUA, Canadá', main_regions: 'Vale do Loire (Muscadet); Oregon, Washington; sul de Ontário',
      description: 'Branco seco e leve; é a uva do Muscadet. DNA: Pinot Blanc × Gouais Blanc.',
      profile: P('seco', 'leve', '', '', ''), aromas_wf: [], aromas_wiki: [] },
    { name: 'Müller-Thurgau', color: 'branca', wiki: 'M%C3%BCller-Thurgau', wf: '',
      origin: 'Criada por Hermann Müller (cantão da Turgóvia, Suíça) em 1882, no instituto de Geisenheim (Alemanha).',
      synonyms: ['Rivaner'],
      main_countries: 'Alemanha, Hungria, Áustria, República Tcheca, Eslováquia, Eslovênia, Luxemburgo, Itália, Inglaterra, Nova Zelândia',
      description: 'Vinhos suaves, de acidez baixa, mas frutados; para beber jovens. DNA: Riesling × Madeleine Royale.',
      profile: P('', '', '', 'baixa', ''), aromas_wf: [], aromas_wiki: [] },
    { name: 'Muscat of Alexandria', color: 'branca', wiki: 'Muscat_of_Alexandria', wf: '',
      origin: 'Norte da África/Egito; uma das videiras mais antigas ainda existentes.',
      synonyms: ['Zibibbo', 'Moscatel de Alejandría', "Muscat d'Alexandrie", 'Gordo Blanco'],
      main_countries: 'Grécia, Itália, Espanha, Austrália, Bolívia, África do Sul', main_regions: 'Lemnos; Pantelleria (Zibibbo), Sicília, Calábria; Málaga, Alicante, Valência, Canárias',
      climate: 'Prospera no calor; amadurece em agosto (hemisfério norte).', disease_sensitivity: 'Oídio.', vigor: 'Muito produtiva.',
      description: 'Sabor marcante de uva; tradicionalmente vinhos doces; também usada em jerez, porto, aguardentes, Moscato, uva de mesa e passas. Mãe/pai do Torrontés Riojano.',
      profile: P('', '', '', '', ''), aromas_wf: [], aromas_wiki: [] },
    { name: 'Trousseau', color: 'tinta', wiki: 'Trousseau_(grape)', wf: '',
      origin: 'Jura (leste da França).',
      synonyms: ['Bastardo', 'Merenzao', 'Cabernet Gros', 'Trousseau Noir'],
      main_countries: 'Portugal (maior área), França (Jura), Espanha, EUA, Austrália',
      description: 'Vermelho-cereja profundo, álcool alto e acidez alta; fruta vermelha, notas de carne seca e mineralidade de musgo. Relação pai/filho com o Savagnin; mãe/pai da Carménère.',
      profile: P('', '', '', 'alta', 'alto'), aromas_wf: [], aromas_wiki: [] },
    { name: 'Marselan', color: 'tinta', wiki: 'Marselan', wf: '',
      origin: 'Criada por Paul Truel em 1961 (INRA, perto de Marseillan, França): Cabernet Sauvignon × Grenache.',
      synonyms: [],
      main_countries: 'França, Espanha, Suíça, EUA, Argentina, Brasil, China', main_regions: 'Languedoc, sul do Rhône; Catalunha; Mendoza',
      disease_sensitivity: 'Muito resistente a oídio, botrytis, desavinho e ácaros.', bunch_size: 'Cachos grandes de bagas pequenas',
      description: 'Vinhos de cor profunda e muito aromáticos, taninos flexíveis, geralmente de corpo médio, com potencial de guarda.',
      profile: P('', 'medio', '', '', ''), aromas_wf: [], aromas_wiki: [] },
    { name: 'Dureza', color: 'tinta', wiki: 'Dureza', wf: '',
      origin: 'Ardèche (centro-sul da França); hoje raríssima.',
      synonyms: [],
      main_countries: 'França (Ardèche, Drôme, Isère)',
      description: 'Pai da Syrah (com a Mondeuse Blanche), confirmado por DNA em 1998 — o que mostrou que a Syrah é francesa. Irmã completa da Teroldego.',
      profile: P('', '', '', '', ''), aromas_wf: [], aromas_wiki: [] },
    { name: 'Mondeuse Blanche', color: 'branca', wiki: 'Mondeuse_blanche', wf: '',
      origin: 'França.', synonyms: [],
      main_countries: 'França', main_regions: 'Savoie (Vin de Savoie), Bugey',
      description: 'Apontada como mãe da Syrah; um sequenciamento genético recente sugere que a relação pode ser mais complexa. Não é parente próxima da Mondeuse Noire. Apenas 5 ha em 1999.',
      profile: P('', '', '', '', ''), aromas_wf: [], aromas_wiki: [] },
    { name: 'Peloursin', color: 'tinta', wiki: 'Peloursin', wf: '',
      origin: 'Isère (perto de Grenoble, França); quase extinta.', synonyms: [],
      main_countries: 'França; pouquíssimo na Califórnia e em Victoria (Austrália)',
      description: 'Cruzada com a Syrah, deu a Durif (Petite Sirah).',
      profile: P('', '', '', '', ''), aromas_wf: [], aromas_wiki: [] },
    { name: 'Ciliegiolo', color: 'tinta', wiki: 'Ciliegiolo', wf: '',
      origin: 'Itália.', synonyms: ['Ciliegino', 'Aleatico di Spagna'],
      main_countries: 'Itália (cerca de 5.000 ha, em declínio)', main_regions: 'Toscana, Úmbria, Sicília, Ligúria',
      description: 'Na Úmbria, tinto leve para o dia a dia; na Toscana, estilo mais estruturado. A relação genética com a Sangiovese é disputada (pai/mãe ou filha).',
      profile: P('', '', '', '', ''), aromas_wf: [], aromas_wiki: [] },
    { name: 'Plavac Mali', color: 'tinta', wiki: 'Plavac_Mali', wf: '',
      origin: 'Costa da Dalmácia (Croácia). DNA (Carole Meredith, UC Davis, 1998): Zinfandel × Dobričić.',
      synonyms: [], main_countries: 'Croácia', main_regions: 'Dingač, Postup, Hvar, Brač, Vis, Komarna, Konavle',
      description: 'Álcool alto (13–17%), rico em taninos; alfarroba, figo, sálvia, cereja escura, pimenta e especiarias; seco, meio seco ou doce.',
      profile: P('', '', 'alto', '', 'alto'), aromas_wf: [], aromas_wiki: ['Figo', 'Sálvia', 'Cereja negra', 'Pimenta-do-reino'] },
    { name: 'Dobričić', color: 'tinta', wiki: 'Dobri%C4%8Di%C4%87', wf: '',
      origin: 'Ilha de Šolta (Dalmácia, Croácia).', synonyms: [], main_countries: 'Croácia',
      description: 'Variedade antiga de tinto; muitas vinhas foram abandonadas depois da Segunda Guerra. É um dos pais da Plavac Mali (com a Zinfandel).',
      profile: P('', '', '', '', ''), aromas_wf: [], aromas_wiki: [] },
    { name: 'Rondinella', color: 'tinta', wiki: 'Rondinella', wf: '',
      origin: 'Vêneto (Itália).', synonyms: [], main_countries: 'Itália', main_regions: 'Valpolicella, Bardolino',
      description: 'Vinhos leves, usados em cortes; as uvas secam bem, por isso é importante no Amarone e no Recioto. DNA confirma a Corvina como mãe/pai.',
      profile: P('', 'leve', '', '', ''), aromas_wf: [], aromas_wiki: [] },
    { name: 'Corvinone', color: 'tinta', wiki: 'Corvinone', wf: '',
      origin: 'Vêneto (Itália).', synonyms: [], main_countries: 'Itália', main_regions: 'Valpolicella, Bardolino',
      description: 'Quase sempre em corte com Corvina, Rondinella e Molinara; boa para secagem (Amarone, Recioto). Já foi tida como clone da Corvina, mas o DNA mostrou que é outra variedade: bagas maiores, cachos mais soltos, amadurece mais tarde (meados de outubro).',
      profile: P('', '', '', '', ''), aromas_wf: [], aromas_wiki: [] },
    { name: 'Listán Prieto', color: 'tinta', wiki: 'List%C3%A1n_Prieto', wf: '',
      origin: 'Provavelmente Castilla-La Mancha (Espanha), século XVI; levada às Américas pela colonização espanhola.',
      synonyms: ['Mission', 'País', 'Criolla Chica', 'Misión'],
      main_countries: 'Ilhas Canárias; historicamente México, Peru, Califórnia, Chile e Argentina',
      description: 'DNA (Madri) mostrou que a Mission/País é geneticamente a Listán Prieto. Mãe/pai do Torrontés Riojano.',
      profile: P('', '', '', '', ''), aromas_wf: [], aromas_wiki: [] },
    { name: 'Ruby Cabernet', color: 'tinta', wiki: 'Ruby_Cabernet', wf: '',
      origin: 'Criada em 1936 por Harold Olmo (UC Davis): Cabernet Sauvignon × Carignan.', synonyms: [],
      main_countries: 'EUA (Califórnia), África do Sul, Austrália, Argentina, Brasil, Chile',
      disease_sensitivity: 'Oídio; má frutificação em algumas regiões.',
      description: 'Boa cor e sabor agradável de cereja; usada sobretudo em vinhos a granel.',
      profile: P('', '', '', '', ''), aromas_wf: [], aromas_wiki: [] },
    { name: 'Auxerrois Blanc', color: 'branca', wiki: 'Auxerrois_blanc', wf: '',
      origin: 'França (provavelmente Lorena).', synonyms: ['Pinot Auxerrois'],
      main_countries: 'França, Alemanha, Luxemburgo', main_regions: 'Alsácia (1.950 ha), Alemanha, Luxemburgo',
      soils: 'Prefere calcário.', bunch_size: 'Pequeno e compacto',
      description: 'Branco seco, muitas vezes em corte com a parecida Pinot Blanc; entra no Crémant d\'Alsace. Irmã completa da Chardonnay (Gouais Blanc × Pinot).',
      profile: P('seco', '', '', '', ''), aromas_wf: [], aromas_wiki: [] }
  ];

  var RELATIONS_V2 = [
    ['parent_of', 'Pinot Blanc', 'Melon de Bourgogne', 'Melon_de_Bourgogne'],
    ['parent_of', 'Teroldego', 'Lagrein', 'Lagrein'],
    ['confused_with', 'Friulano', 'Sauvignon Blanc', 'Sauvignonasse',
      'No Chile, vinhas vendidas como Sauvignon Blanc eram Friulano (Sauvignonasse). Pela Wine Folly, o Friulano é leve e herbáceo (grapefruit, pera verde, estragão); o Sauvignon Blanc tem groselha espinhosa, maracujá e melão.'],
    ['confused_with', 'Verdicchio', 'Trebbiano Toscano', 'Verdicchio', 'Às vezes são confundidos. Os dois têm acidez alta; o Verdicchio costuma mostrar limão e amêndoa amarga.'],
    ['confused_with', 'Teroldego', 'Lagrein', 'Teroldego', 'Estilos parecidos: tintos escuros do Trentino-Alto Adige. O Teroldego tem taninos macios e redondos; o Lagrein é muito tânico e de acidez alta.'],
    ['confused_with', 'Greco', 'Viognier', 'Greco_(grape)', 'O Greco é descrito como "vagamente parecido com o Viognier": aromático, com pêssego.'],
    ['confused_with', 'Pinot Blanc', 'Chardonnay', 'Pinot_blanc', 'Vinificação parecida e confusão histórica. O Pinot Blanc tem acidez mais alta e aromas de maçã, cítricos e flores.']
  ];

  // Relações da v1 que a pesquisa da v2 mostrou erradas ou disputadas (serão removidas).
  var REMOVED_V2 = [
    ['parent_of', 'Pinot Noir', 'Melon de Bourgogne'],
    ['parent_of', 'Ciliegiolo', 'Sangiovese'],
    ['parent_of', 'Calabrese Montenuovo', 'Sangiovese']
  ];

  grapes = grapes.concat(GRAPES_V2);
  relations = relations.concat(RELATIONS_V2);

  return { version: 2, WIKI: WIKI, WF: WF, EXTRA_AROMAS: EXTRA_AROMAS, grapes: grapes, relations: relations, removed_relations: REMOVED_V2 };
})();
